return {
	["napalm"] = {
		useDefaultExplosions = false,
		fireball = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			air        = true,
			ground     = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.87,
				colormap            = [[1 1 1 0.1   1 1 1 0.1   1 1 1 0.1   1 1 1 0.1   0 0 0 0   0 0 0 0]],
				directional        = false,
				emitrot            = 0,
				emitrotspread      = 0,
				emitvector         = [[0, 0, 0]],
				gravity            = [[0, 0.1, 0]],
				numparticles       = 1,
				particlelife       = 150,
				particlelifespread = 30,
				particlesize       = 120,
				particlesizespread = 1,
				particlespeed      = 2,
				particlespeedspread = 6,
				pos                = [[0, 1, 0]],
				rotParams           = [[1, 1, 1]],
				animParams          = [[6,6,60]], --[xTiles, yTiles, animLength in game frames]
				sizegrowth          = 0.1,
				sizemod             = 1,
				texture             = [[generated-furnace]],
				drawOrder           = 0,
			},
		},

		brightflare = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = true,
			water              = true,
			properties = {
				colormap            = [[1 1 1 0.1   1 1 1 0.1   1 1 1 0.1   1 1 1 0.1   0 0 0 0]],
				dir                = [[0, 1, 0]],
				--gravity            = [[0.0, 0.1, 0.0]],
				frontoffset        = 0,
				animParams          = [[6,6,60]], --[xTiles, yTiles, animLength in game frames]
				fronttexture       = [[generated-furnace]],
				length             = 40,
				sidetexture        = [[none]],
				size               = 120,
				sizegrowth         = 0,
				ttl                = 150,
				pos                = [[0, 3, 0]],
				--rotParams          = [[-10 r20, -20 r40, -180 r360]],
				drawOrder          = 0,
			},
		},
	},

	["napalmsmall"] = {
		useDefaultExplosions = false,
		fireball = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			air        = true,
			ground     = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.87,
				colormap            = [[1 1 1 0.1   1 1 1 0.1   1 1 1 0.1   1 1 1 0.1   0 0 0 0   0 0 0 0]],
				directional        = false,
				emitrot            = 0,
				emitrotspread      = 0,
				emitvector         = [[0, 0, 0]],
				gravity            = [[0, 0.1, 0]],
				numparticles       = 1,
				particlelife       = 30,
				particlelifespread = 30,
				particlesize       = 30,
				particlesizespread = 1,
				particlespeed      = 2,
				particlespeedspread = 6,
				pos                = [[0, 1, 0]],
				rotParams           = [[1, 1, 1]],
				animParams          = [[6,6,60]], --[xTiles, yTiles, animLength in game frames]
				sizegrowth          = 0.1,
				sizemod             = 1,
				texture             = [[generated-furnace]],
				drawOrder           = 0,
			},
		},

		brightflare = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = true,
			water              = true,
			properties = {
				colormap            = [[1 1 1 0.1   1 1 1 0.1   1 1 1 0.1   1 1 1 0.1   0 0 0 0]],
				dir                = [[0, 1, 0]],
				--gravity            = [[0.0, 0.1, 0.0]],
				frontoffset        = 0,
				animParams          = [[6,6,60]], --[xTiles, yTiles, animLength in game frames]
				fronttexture       = [[generated-furnace]],
				length             = 40,
				sidetexture        = [[none]],
				size               = 30,
				sizegrowth         = 0,
				ttl                = 30,
				pos                = [[0, 3, 0]],
				--rotParams          = [[-10 r20, -20 r40, -180 r360]],
				drawOrder          = 0,
			},
		},
	},
}

