return {

	["mex-fireball-small-blue"] = {
		flame = {
			air        = true,
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			properties = {
				airdrag             = 0.97,
				colormap            = [[0 0 0 0     0.7 0.7 0.7 1     0 0 1 1     0 0 0 0]],
				directional         = false,
				emitrot             = 0,
				emitrotspread       = 0,
				emitvector          = [[0,0,0]],
				gravity             = [[0,0,0]],
				numparticles        = [[1]],
				particlelife        = 64,
				particlelifespread  = 0,
				particlesize        = 20,
				particlesizespread  = 1,
				particlespeed       = 0,
				particlespeedspread = 0,
				sizegrowth          = 0,
				sizemod             = 1,
				rotParams           = [[-24 r48, -60 r120, -180 r360]],
				animParams          = [[4,4,16]], --[xTiles, yTiles, animLength in game frames]
				pos                 = [[0,4,0]],
				texture             = [[generated-generator]],
				drawOrder           = 0,
			},

		},
	},

	["mex-fireball-small-orange"] = {
		flame = {
			air        = true,
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			properties = {
				airdrag             = 0.97,
				colormap            = [[0 0 0 0     0.7 0.7 0.7 1     1 0.6 0 1     0 0 0 0]],
				directional         = false,
				emitrot             = 0,
				emitrotspread       = 0,
				emitvector          = [[0,0,0]],
				gravity             = [[0,0,0]],
				numparticles        = [[1]],
				particlelife        = 64,
				particlelifespread  = 0,
				particlesize        = 20,
				particlesizespread  = 1,
				particlespeed       = 0,
				particlespeedspread = 0,
				sizegrowth          = 0,
				sizemod             = 1,
				rotParams           = [[-24 r48, -60 r120, -180 r360]],
				animParams          = [[4,4,16]], --[xTiles, yTiles, animLength in game frames]
				pos                 = [[0,4,0]],
				texture             = [[generated-generator]],
				drawOrder           = 0,
			},
		},
	},

	["mex-fireball-small-purple"] = {
		flame = {
			air        = true,
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			properties = {
				airdrag             = 0.97,
				colormap            = [[0 0 0 0     0.7 0.7 0.7 1       1 0 0.6 1     0 0 0 0]],
				directional         = false,
				emitrot             = 0,
				emitrotspread       = 0,
				emitvector          = [[0,0,0]],
				gravity             = [[0,0,0]],
				numparticles        = [[1]],
				particlelife        = 64,
				particlelifespread  = 0,
				particlesize        = 20,
				particlesizespread  = 1,
				particlespeed       = 0,
				particlespeedspread = 0,
				sizegrowth          = 0,
				sizemod             = 1,
				rotParams           = [[-24 r48, -60 r120, -180 r360]],
				animParams          = [[4,4,16]], --[xTiles, yTiles, animLength in game frames]
				pos                 = [[0,4,0]],
				texture             = [[generated-generator]],
				drawOrder           = 0,
			},
		},
	},

	["mex-fireball-small-green"] = {
		flame = {
			air        = true,
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			properties = {
				airdrag             = 0.97,
				colormap            = [[0 0 0 0     0.7 0.7 0.7 1       0 1 0 0.5       0 0 0 0]],
				directional         = false,
				emitrot             = 0,
				emitrotspread       = 0,
				emitvector          = [[0,0,0]],
				gravity             = [[0,0,0]],
				numparticles        = [[1]],
				particlelife        = 64,
				particlelifespread  = 0,
				particlesize        = 20,
				particlesizespread  = 1,
				particlespeed       = 0,
				particlespeedspread = 0,
				sizegrowth          = 0,
				sizemod             = 1,
				rotParams           = [[-24 r48, -60 r120, -180 r360]],
				animParams          = [[4,4,16]], --[xTiles, yTiles, animLength in game frames]
				pos                 = [[0,4,0]],
				texture             = [[generated-generator]],
				drawOrder           = 0,
			},
		},
	},

	["powerplant-fireball-small-orange"] = {
		flame = {
			air        = true,
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			properties = {
				airdrag             = 0.97,
				colormap            = [[0 0 0 0     0.7 0.7 0.7 1     1 0.6 0 1     0 0 0 0]],
				directional         = false,
				emitrot             = 0,
				emitrotspread       = 0,
				emitvector          = [[0,0,0]],
				gravity             = [[0,0,0]],
				numparticles        = [[1]],
				particlelife        = 64,
				particlelifespread  = 0,
				particlesize        = 10,
				particlesizespread  = 1,
				particlespeed       = 0,
				particlespeedspread = 0,
				sizegrowth          = 0,
				sizemod             = 1,
				rotParams           = [[-24 r48, -60 r120, -180 r360]],
				animParams          = [[4,4,16]], --[xTiles, yTiles, animLength in game frames]
				pos                 = [[0,4,0]],
				texture             = [[generated-generator]],
				drawOrder           = 0,
			},

		},
	},

	["powerplant-fireball-small-purple"] = {
		flame = {
			air        = true,
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			properties = {
				airdrag             = 0.97,
				colormap            = [[0 0 0 0     0.7 0.7 0.7 1       1 0 0.6 1     0 0 0 0]],
				directional         = false,
				emitrot             = 0,
				emitrotspread       = 0,
				emitvector          = [[0,0,0]],
				gravity             = [[0,0,0]],
				numparticles        = [[1]],
				particlelife        = 64,
				particlelifespread  = 0,
				particlesize        = 10,
				particlesizespread  = 1,
				particlespeed       = 0,
				particlespeedspread = 0,
				sizegrowth          = 0,
				sizemod             = 1,
				rotParams           = [[-24 r48, -60 r120, -180 r360]],
				animParams          = [[4,4,16]], --[xTiles, yTiles, animLength in game frames]
				pos                 = [[0,4,0]],
				texture             = [[generated-generator]],
				drawOrder           = 0,
			},
		},
	},

	["powerplant-fireball-large-green"] = {
		flame = {
			air        = true,
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			properties = {
				airdrag             = 0.97,
				colormap            = [[0 0 0 0     0.7 0.7 0.7 1       0 1 0 0.5       0 0 0 0]],
				directional         = false,
				emitrot             = 0,
				emitrotspread       = 0,
				emitvector          = [[0,0,0]],
				gravity             = [[0,0,0]],
				numparticles        = [[1]],
				particlelife        = 64,
				particlelifespread  = 0,
				particlesize        = 40,
				particlesizespread  = 1,
				particlespeed       = 0,
				particlespeedspread = 0,
				sizegrowth          = 0,
				sizemod             = 1,
				rotParams           = [[-24 r48, -60 r120, -180 r360]],
				animParams          = [[4,4,16]], --[xTiles, yTiles, animLength in game frames]
				pos                 = [[0,4,0]],
				texture             = [[generated-generator]],
				drawOrder           = 0,
			},
		},
	},

	["powerplant-fireball-large"] = {
		flame = {
			air        = true,
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			properties = {
				airdrag             = 0.97,
				colormap            = [[0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
				directional         = false,
				emitrot             = 70,
				emitrotspread       = 40,
				emitvector          = [[0,0,0]],
				gravity             = [[0,0,0]],
				numparticles        = [[1]],
				particlelife        = 40,
				particlelifespread  = 0,
				particlesize        = 40,
				particlesizespread  = 1,
				particlespeed       = 0,
				particlespeedspread = 0,
				rotParams           = [[-24 r48, -60 r120, -180 r360]],
				animParams          = [[4,4,40]], --[xTiles, yTiles, animLength in game frames]
				pos                 = [[0,0,0]],
				sizegrowth          = 0,
				sizemod             = 1,
				texture             = [[generated-fireball]],
				drawOrder           = 0,
			},

		},
	},
}