local a = 97
local b = 98
local c = 99
local d = 100
local e = 101
local f = 102
local g = 103
local h = 104
local i = 105
local j = 106
local k = 107
local l = 108
local m = 109
local n = 110
local o = 111
local p = 112
local q = 113
local r = 114
local s = 115
local t = 116
local u = 117
local v = 118
local w = 119
local x = 120
local y = 121
local z = 122

nameToKeyCode = {
	eairplant = {f, p},
	f1landfac = {f, l},
	f2landfac = {f, l},

	etech1 = {b, t},
	emetalextractor = {e, m},
	esolar2 = {e, s},
	egeothermal = {e, g},
	efusion2 = {e, f},
	estorage = {e, d},

	eradar2 = {b, r},
	ejammer2 = {b, j},
	ekmar = {b, k},
	emine = {v, m},
	elightturret2 = {v, p},
	eheavyturret2 = {v, i},
	elaserbattery = {v, b},
	eartyturret = {v, l},
	eshieldgen = {v, a},
	esilo = {v, s},
	ehbotengineer = {b, e},
	fedengineer = {b, e},
	lozengineer = {b, e},
}
