
-- Control Victory Options
{
	key    = 'controlvictoryoptions',
	name   = 'Control Victory Options',
	desc   = 'Allows you to control at a granular level the individual options for Control Point Victory',
	type   = 'section',
},
{
key="scoremode",
name="Scoring Mode (Control Victory Points)",
desc="Defines how the game is played",
type="list",
def="disabled",
section="controlvictoryoptions",
items={
{key="disabled", name="Disabled", desc="Disable Control Points as a victory condition."},
{key="countdown", name="Countdown", desc="A Control Point decreases all opponents' scores, zero means defeat."},
{key="tugofwar", name="Tug of War", desc="A Control Point steals enemy score, zero means defeat."},
{key="domination", name="Domination", desc="Holding all Control Points will grant 1000 score, first to reach the score limit wins."},
}
},
{
key    = 'limitscore',
name   = 'Total Score',
desc   = 'Total score amount available.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 3500,
min    = 500,
max    = 5000,
step   = 1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = "numberofcontrolpoints",
name   = "Set number of Control Points on the map",
desc   = "Sets the number of control points on the map and scales the total score amount to match. Has no effect if Preset map configs are enabled.",
section= "controlvictoryoptions",
type="list",
def="7",
section= "controlvictoryoptions",
items={
{key="7", name="7", desc=""},
{key="13", name="13", desc=""},
{key="19", name="19", desc=""},
{key="25", name="25", desc=""},
}
},
{
key    = "usemapconfig",
name   = "Use preset map-specific Control Point locations?",
desc   = "Should the control point config for this map be used instead of autogenerated control points?",
type="list",
def="disabled",
section= "controlvictoryoptions",
items={
{key="disabled", name="Disabled", desc="This will tell the game to use autogenerated control points."},
{key="enabled", name="Enabled", desc="This will tell the game to use preset map control points (Set via map config)."},
}
},
{
key    = 'captureradius',
name   = 'Capture Radius',
desc   = 'Radius around a point in which to capture it.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 500,
min    = 100,
max    = 1000,
step   = 25,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'capturetime',
name   = 'Capture Time',
desc   = 'Time to capture a point.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 30,
min    = 1,
max    = 60,
step   = 1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'capturebonus',
name   = 'Capture Bonus',
desc   = 'Percentage of how much faster capture takes place by adding more units.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 5,
min    = 1,
max    = 100,
step   = 1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'decapspeed',
name   = 'De-Cap Speed',
desc   = 'Speed multiplier for neutralizing an enemy point.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 2,
min    = 1,
max    = 3,
step   = 1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'starttime',
name   = 'Start Time',
desc   = 'Number of seconds until control points can be captured.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 180,
min    = 0,
max    = 300,
step   = 1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'metalperpoint',
name   = 'Metal given to each player per captured point',
desc   = 'Each player on an allyteam that has captured a point will receive this amount of resources per point captured per second',
type   = 'number',
section= 'controlvictoryoptions',
def    = 0,
min    = 0,
max    = 20,
step   = 0.1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'energyperpoint',
name   = 'Energy given to each player per captured point',
desc   = 'Each player on an allyteam that has captured a point will receive this amount of resources per point captured per second',
type   = 'number',
section= 'controlvictoryoptions',
def    = 0,
min    = 0,
max    = 20,
step   = 0.1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'dominationscoretime',
name   = 'Domination Score Time',
desc   = 'Time needed holding all points to score in multi domination.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 30,
min    = 1,
max    = 60,
step   = 1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'tugofwarmodifier',
name   = 'Tug of War Modifier',
desc   = 'The amount of score transfered between opponents when points are captured is multiplied by this amount.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 2,
min    = 0,
max    = 6,
step   = 1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
{
key    = 'dominationscore',
name   = 'Score awarded for Domination',
desc   = 'The amount of score awarded when you have scored a domination.',
type   = 'number',
section= 'controlvictoryoptions',
def    = 1000,
min    = 500,
max    = 1000,
step   = 1,  -- quantization is aligned to the def value
-- (step <= 0) means that there is no quantization
},
-- End Control Victory Options