unitDef                     = {

	activatewhenbuilt             = false,
	buildAngle                    = 1024,
	buildCostEnergy               = 0,
	buildCostMetal                = buildCostMetal,
	builder                       = true,
	buildTime                     = 5,
	buildpic					 = "ebasefactory.png",
	canAttack			          = false,
	canBeAssisted                 = false,
	canGuard                      = true,
	canMove                       = true,
	canPatrol                     = true,
	canReclaim		              = false,
	canstop                       = true,
	category                      = "BUILDING",
	description                   = [[Build a Tech Facility to unlock units. Build Supply Depots to increase your army size.]],
	energyStorage                 = 0,
	energyUse                     = 0,
	energyMake                    = 0,
	explodeAs                     = explodeAs,
	footprintX                    = 12,
	footprintZ                    = 12,
	floater			              = false,
	iconType                      = "structurefactoryt0",
	idleAutoHeal                  = .5,
	idleTime                      = 2200,
	maxDamage                     = 100,
	maxSlope                      = 20,
	maxWaterDepth                 = 0,
	metalStorage                  = 0,
	metalMake                     = 0,
	moveState					  = 0,
	name                          = humanName,
	objectName                    = objectName,
	script						  = script,
	radarDistance                 = 0,
	repairable		              = false,
	selfDestructAs                = explodeAs,
	showNanoSpray                 = true,
	side                          = "CORE",
	sightDistance                 = 388,
	smoothAnim                    = true,
	TEDClass                      = "PLANT",
	unitname                      = unitName,
	--  unitRestricted	          = 1,
	workerTime                    = workertime,
	yardMap                       = "cccccccccccc cccccccccccc cccccccccccc cccccccccccc cccccccccccc cccccccccccc cccccccccccc cccccccccccc cccccccccccc cccccccccccc cccccccccccc cccccccccccc",
	--  usePieceCollisionVolumes  = true,
	--  modelCenterOffset	      = {108, 10, 0},
	sfxtypes                      = { 
		pieceExplosionGenerators  = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators       = {
			"custom:nano-animated",
			"custom:nano-animated",
			"custom:blacksmoke",
			"custom:fusionreactionbasic",
		},
	},
	buildoptions = hoverFactoryBuildList,
	sounds                        = {
		underattack               = "units_under_attack",
		select                    = {
			"building_select_factory",
		},
	},
	weapons                       = {
	},
	customParams                  = {
		unitguide = [[The Land Factory is the Loz Alliance's primary ground production facility, responsible for producing the full range of land units available at its current tech tier. It requires a Tech Facility to unlock higher-tier units and Supply Depots to field a larger army. Running two factories in parallel when metal income allows it dramatically accelerates unit production. Losing a factory is a serious setback — keep it away from the front.]],
		unittype				  = "building",
		unitrole 				  = "Factory",
		buildmenucategory		  = "Production",
		RequireTech              = tech,
		death_sounds              = "generic",
		normaltex                = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                 = "unittextures/lego2skin_explorerbucket.dds",
		factionname	              = "Loz Alliance",
		
	},
	useGroundDecal                = true,
}
