unitDef                    = {
	--mobileunit 
	transportbyenemy             = false; 
	--**
	buildCostEnergy              = 0,
	buildCostMetal               = buildCostMetal,
	buildDistance                = builddistance,
	builder                      = true,
	buildTime                    = 2.5,
	buildpic					 = buildpicture,
	capturable		             = false,
	CanAttack			         = true,
	CanAssist			         = true,
	canBeAssisted                = true,
	CanCapture                   = true,
	CanRepair			         = true,
	canRestore					 = true,

	cantBeTransported            = true,

	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canreclaim		             = true,
	canstop                      = true,
	category                     = "GROUND",
	description                  = [[Builds Units]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = explodeas,
	footprintX                   = footprintx,
	footprintZ                   = footprintz,
	iconType                     = "commander",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	levelground                  = true,
	maxDamage                    = 1,
	maxSlope                     = 180,
	maxVelocity                  = maxvelocity,
	maxReverseVelocity           = 1,
	maxWaterDepth                = 5000,
	metalmake                    = 0,
	metalStorage                 = 0,
	movementClass                = movementclass,
	moveState			         = "0",
	name                         = humanname,
	noChaseCategories	         = "NOTAIR SUPPORT VTOL AMPHIB",
	objectName                   = objectname,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = selfdestructas,
	selfDestructCountdown         = 15,
	showPlayerName	             = true,
	showNanoSpray                = true,
	sightDistance                = 500,
	smoothAnim                   = true,
	stealth			             = true,
	seismicSignature             = 2,
	unitname                     = unitName,
	upright                      = false,
	workerTime                   = workertime,
	TerraformSpeed               = 2147000,
	--------------
	-- Movement --
	--------------
	acceleration 				 = 2,
	brakeRate                    = 0.1,
	turninplace 				 = true,
	turninplacespeedlimit 		 = 10,
	turnInPlaceAngleLimit		 = 45,
	turnrate 				 	 = 600,
	--------------
	--------------

	sfxtypes                     = {
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 
		
		explosiongenerators      = {
			"custom:nanoorb",
			"custom:emptydirt",
			"custom:burnblacksmall",
			"custom:gdhcannon",
		},
	},
	buildoptions                 = buildlist,
	sounds                       = {
		build					 = "miscfx/buildstart",
		underattack              = "units_under_attack",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = weapon1,
			onlyTargetCategory    = "GROUND SHIP",
		},
	},
	customParams                 = {
		unittype				 = "mobile",
		unitrole				 = "Commander",
		area_mex_def			 = areamexdef,
		ProvideTech              = techprovided,
		RequireTech				 = techrequired,
		stockpileLimit           = 5,
		techlevel                = techlevel,
		--hpoverride               = hp,
		iscommander              = true,
		needed_cover             = 2,
		death_sounds             = "commander",
		factionname	             = "Loz Alliance",
		--removeattack             = "true",
		--removerepair             = "true",
		nofriendlyfire	         = "1",
		normaltex               = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		unitguide = [[The Loz Alliance Commander is the player's starting unit and the irreplaceable center of every match. It builds all structures, repairs friendly units, reclaims wreckage, and captures enemy buildings, while its heat ray weapon accumulates thermal stress on targets with every burst — a sufficiently overheated unit will malfunction and shut down entirely. The Commander upgrades through four tiers alongside tech progression, gaining range and dramatically increased damage output at each step. Losing the Commander ends the game; using it aggressively while keeping it alive is the defining challenge of every match.]],
	},
}

--------------------------------------------------------------------------------

weaponDefs                 = {
	commgun           = {
		edgeeffectiveness        = 0.1,
		hardstop                  = true,
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		duration                  = 0.1,
		burst                     = 15,
		burstrate                 = 0.1,
		energypershot             = 50,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 0.1,
		name                      = "High Intensity WaveLaser",
		range                     = 400,
		reloadtime                = 5,
		WeaponType                = "LaserCannon",
		rgbColor                  = purple,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "flashpointheatray",
		soundHit                  = "phasegun1hit",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 5,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 2000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= smallExplosion, -- In Elmos
			expl_light_life		= smallExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
			heatweapon = "1",
			heatmult   = "1.0", -- optional; higher = heats faster per damage
			weaponguide = [[A heatray capable of superheating targets until they have a catastrophic meltdown.]],
		},
		damage                    = {
			default               = 70,
		},
	},

	commgun_up1               = {
		edgeeffectiveness        = 0.1,
		hardstop                  = true,
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		duration                  = 0.1,
		burst                     = 15,
		burstrate                 = 0.1,
		energypershot             = 50,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 0.1,
		name                      = "High Intensity WaveLaser",
		range                     = 600,
		reloadtime                = 5,
		WeaponType                = "LaserCannon",
		rgbColor                  = purple,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "flashpointheatray",
		soundHit                  = "phasegun1hit",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 10,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 2000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= smallExplosion, -- In Elmos
			expl_light_life		= smallExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
			heatweapon = "1",
			heatmult   = "1.0", -- optional; higher = heats faster per damage
			weaponguide = [[A heatray capable of superheating targets until they have a catastrophic meltdown.]],
		},
		damage                    = {
			default               = 60,
		},
	},

	commgun_up2               = {
		edgeeffectiveness        = 0.1,
		hardstop                  = true,
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		duration                  = 0.1,
		burst                     = 15,
		burstrate                 = 0.1,
		energypershot             = 50,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 0.1,
		name                      = "High Intensity WaveLaser",
		range                     = 650,
		reloadtime                = 5,
		WeaponType                = "LaserCannon",
		rgbColor                  = purple,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "flashpointheatray",
		soundHit                  = "phasegun1hit",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 15,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 2000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= mediumExplosion, -- In Elmos
			expl_light_life		= mediumExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
			heatweapon = "1",
			heatmult   = "1.0", -- optional; higher = heats faster per damage
			weaponguide = [[A heatray capable of superheating targets until they have a catastrophic meltdown.]],
		},
		damage                    = {
			default               = 500,
		},
	},

	commgun_up3               = {
		edgeeffectiveness        = 0.1,
		hardstop                  = true,
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		duration                  = 0.1,
		burst                     = 15,
		burstrate                 = 0.1,
		energypershot             = 50,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 0.1,
		name                      = "High Intensity WaveLaser",
		range                     = 700,
		reloadtime                = 5,
		WeaponType                = "LaserCannon",
		rgbColor                  = purple,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "flashpointheatray",
		soundHit                  = "phasegun1hit",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 20,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 2000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
			heatweapon = "1",
			heatmult   = "1.0", -- optional; higher = heats faster per damage
			weaponguide = [[A heatray capable of superheating targets until they have a catastrophic meltdown.]],
		},
		damage                    = {
			default               = 1750,
		},
	},

	commgun_up4               = {
		edgeeffectiveness        = 0.1,
		hardstop                  = true,
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		duration                  = 0.1,
		burst                     = 15,
		burstrate                 = 0.1,
		energypershot             = 50,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 0.1,
		name                      = "High Intensity WaveLaser",
		range                     = 750,
		reloadtime                = 5,
		WeaponType                = "LaserCannon",
		rgbColor                  = purple,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "flashpointheatray",
		soundHit                  = "phasegun1hit",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 25,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 2000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= hugeExplosion, -- In Elmos
			expl_light_life		= hugeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
			heatweapon = "1",
			heatmult   = "1.0", -- optional; higher = heats faster per damage
			weaponguide = [[A heatray capable of superheating targets until they have a catastrophic meltdown.]],
		},
		damage                    = {
			default               = 4650,
		},
	},
}