unitDef                    = {
	--mobileunit 
	transportbyenemy             = false; 
	--**
	buildCostEnergy              = 0,
	buildCostMetal               = buildCostMetal,
	buildDistance                = builddistance,
	builder                      = true,
	buildTime                    = 2.5,
	buildpic					 = buildpicture,
	capturable		             = false,
	CanAttack			         = true,
	CanAssist			         = true,
	canBeAssisted                = true,
	CanCapture                   = false,
	CanRepair			         = true,
	canRestore					 = true,
	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canreclaim		             = true,
	canstop                      = true,
	category                     = "GROUND",
	description                  = [[Builds Units]],
	energyMake                   = 10,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = explodeas,
	footprintX                   = footprintx,
	footprintZ                   = footprintz,
	iconType                     = "commander",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	levelground                  = true,
	maxDamage                    = 1,
	maxSlope                     = 180,
	maxVelocity                  = maxvelocity,
	maxReverseVelocity           = 1,
	maxWaterDepth                = 5000,
	metalmake                    = 2,
	metalStorage                 = 0,
	movementClass                = movementclass,
	moveState			         = "0",
	name                         = humanname,
	noChaseCategories	         = "NOTAIR SUPPORT VTOL AMPHIB",
	--------------------------
	-- Skillshot (aka DGun) --
	--------------------------
	noAutoFire                   = true,
	fireState                    = 0,
	canManualFire                = true,
	--------------------------
	--------------------------
	objectName                   = objectname,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = selfdestructas,
	selfDestructCountdown         = 15,
	showPlayerName	             = true,
	showNanoSpray                = true,
	sightDistance                = 500,
	smoothAnim                   = true,
	stealth			             = true,
	seismicSignature             = 2,
	unitname                     = unitName,
	upright                      = false,
	workerTime                   = workertime,
	TerraformSpeed               = 2147000,
	--------------
	-- Movement --
	--------------
	acceleration 				 = 2,
	brakeRate                    = 0.1,
	turninplace 				 = true,
	turninplacespeedlimit 		 = 10,
	turnInPlaceAngleLimit		 = 45,
	turnrate 				 	 = 600,
	--------------
	--------------
	sfxtypes                     = {
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 
		
		explosiongenerators      = {
			"custom:nanoorb",
			"custom:emptydirt",
			"custom:burnblacksmall",
			"custom:gdhcannon",
		},
	},
	buildoptions                 = buildlist,
	sounds                       = {
		build					 = "miscfx/buildstart",
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = weapon1,
			badTargetCategory     = "BUILDING",
			onlyTargetCategory    = "GROUND BUILDING SHIP",
		},
		[2]                      = {
			def                  = weapon2,
		},

	},
	customParams                 = {
		unittype				 = "mobile",
		unitrole				 = "Commander",
		area_mex_def			 = areamexdef,
		ProvideTech              = techprovided,
		RequireTech				 = techrequired,
		techlevel                = techlevel,
		canbetransported 		 = "true",
		iscommander              = true,
		hpoverride               = hp,
		buildcostenergyoverride  = buildCostEnergy,
		needed_cover             = 2,
		death_sounds             = "generic",
		factionname	             = "Loz Alliance",

		nofriendlyfire	         = "1",
		normaltex               = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
	},
}

--------------------------------------------------------------------------------

weaponDefs                 = {
	commrailgun           = {
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.5,
		commandfire               = true,
		-- cegtag					  = "burnblack",
		-- beamDecay                 = 0.9,
		beamtime				  = 0.5,
		beamttl                   = 10,
		largebeamlaser			  = true,
		laserFlareSize            = 3,
		sweepfire				  = false,
		duration                  = 0.8,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity BeamLaser",
		range                     = 300,
		reloadtime                = 1,
		WeaponType                = "BeamLaser",
		rgbColor                  = purple,
		rgbColor2                 = "0.25 0.25 0.25",
		soundTrigger              = true,
		soundstart                = "scifi_rifle_laser_B_single_01",
		-- soundHit                  = "explode5",
		-- sprayangle				  = 500,
		texture1                  = "lightning",
		texture2                  = "flash1",
		texture3                  = "flash1",
		texture4                  = "flash1",
		thickness                 = 3,
		tolerance                 = 500,
		turret                    = true,
		weaponVelocity            = 750,
		waterweapon				 = false,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                    = {
			default               = 300,
		},
	},

	commshield                        = {

		Smartshield               = true,
		Exteriorshield            = true,
		Visibleshield             = false,
		Visibleshieldrepulse      = false,
		ShieldStartingPower       = 4125,
		Shieldenergyuse           = 0,
		Shieldradius              = shieldradius,
		Shieldpower               = 8250,
		Shieldpowerregen          = 150,
		Shieldpowerregenenergy    = 0,
		rechargeDelay		  	  = 80,
		Shieldintercepttype       = 4,
		Shieldgoodcolor           = "0.0 0.2 1.0",
		Shieldbadcolor            = "1.0 0 0",
		Shieldalpha              = 0.2,

		texture1		          = "shield4",

		visibleShieldHitFrames    = 1,
		weaponType                = [[Shield]],
		damage                    = {
			default               = 1,
		},
	},

	commrailgun_up1               = {
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.5,
		commandfire               = true,
		-- cegtag					  = "burnblack",
		-- beamDecay                 = 0.9,
		beamtime				  = 0.5,
		beamttl                   = 10,
		largebeamlaser			  = true,
		laserFlareSize            = 3,
		sweepfire				  = false,
		duration                  = 0.8,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity BeamLaser",
		range                     = 500,
		reloadtime                = 2.5,
		WeaponType                = "BeamLaser",
		rgbColor                  = purple,
		rgbColor2                 = "0.25 0.25 0.25",
		soundTrigger              = true,
		soundstart                = "scifi_rifle_laser_B_single_01",
		-- soundHit                  = "explode5",
		-- sprayangle				  = 500,
		texture1                  = "lightning",
		texture2                  = "flash1",
		texture3                  = "flash1",
		texture4                  = "flash1",
		thickness                 = 4,
		tolerance                 = 500,
		turret                    = true,
		weaponVelocity            = 750,
		waterweapon				 = false,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                    = {
			default               = 400,
		},
	},

	commshield_up1                        = {

		Smartshield               = true,
		Exteriorshield            = true,
		Visibleshield             = false,
		Visibleshieldrepulse      = false,
		ShieldStartingPower       = 8250,
		Shieldenergyuse           = 0,
		Shieldradius              = shieldradius,
		Shieldpower               = 14000,
		Shieldpowerregen          = 200,
		Shieldpowerregenenergy    = 0,
		rechargeDelay		  	  = 60,
		Shieldintercepttype       = 4,
		Shieldgoodcolor           = "0.0 0.2 1.0",
		Shieldbadcolor            = "1.0 0 0",
		Shieldalpha              = 0.2,

		texture1		          = "shield4",

		visibleShieldHitFrames    = 1,
		weaponType                = [[Shield]],
		damage                    = {
			default               = 1,
		},
	},

	commrailgun_up2               = {
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.5,
		commandfire               = true,
		-- cegtag					  = "burnblack",
		-- beamDecay                 = 0.9,
		beamtime				  = 0.5,
		beamttl                   = 10,
		largebeamlaser			  = true,
		laserFlareSize            = 4,
		sweepfire				  = false,
		duration                  = 0.8,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-medium",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity BeamLaser",
		range                     = 600,
		reloadtime                = 7.5,
		WeaponType                = "BeamLaser",
		rgbColor                  = purple,
		rgbColor2                 = "0.25 0.25 0.25",
		soundTrigger              = true,
		soundstart                = "scifi_rifle_laser_B_single_01",
		-- soundHit                  = "explode5",
		-- sprayangle				  = 500,
		texture1                  = "lightning",
		texture2                  = "flash1",
		texture3                  = "flash1",
		texture4                  = "flash1",
		thickness                 = 6,
		tolerance                 = 500,
		turret                    = true,
		weaponVelocity            = 750,
		waterweapon				 = false,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                    = {
			default               = 8100,
		},
	},

	commshield_up2                        = {

		Smartshield               = true,
		Exteriorshield            = true,
		Visibleshield             = false,
		Visibleshieldrepulse      = false,
		ShieldStartingPower       = 14000,
		Shieldenergyuse           = 0,
		Shieldradius              = shieldradius,
		Shieldpower               = 23000,
		Shieldpowerregen          = 325,
		Shieldpowerregenenergy    = 0,
		rechargeDelay		  	  = 60,
		Shieldintercepttype       = 4,
		Shieldgoodcolor           = "0.0 0.2 1.0",
		Shieldbadcolor            = "1.0 0 0",
		Shieldalpha              = 0.2,

		texture1		          = "shield4",

		visibleShieldHitFrames    = 1,
		weaponType                = [[Shield]],
		damage                    = {
			default               = 1,
		},
	},

	commrailgun_up3               = {
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.5,
		commandfire               = true,
		-- cegtag					  = "burnblack",
		-- beamDecay                 = 0.9,
		beamtime				  = 0.5,
		beamttl                   = 10,
		largebeamlaser			  = true,
		laserFlareSize            = 5,
		sweepfire				  = false,
		duration                  = 0.8,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-large",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity BeamLaser",
		range                     = 700,
		reloadtime                = 15,
		WeaponType                = "BeamLaser",
		rgbColor                  = purple,
		rgbColor2                 = "0.25 0.25 0.25",
		soundTrigger              = true,
		soundstart                = "scifi_rifle_laser_B_single_01",
		-- soundHit                  = "explode5",
		-- sprayangle				  = 500,
		texture1                  = "lightning",
		texture2                  = "flash1",
		texture3                  = "flash1",
		texture4                  = "flash1",
		thickness                 = 8,
		tolerance                 = 500,
		turret                    = true,
		weaponVelocity            = 750,
		waterweapon				 = false,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                    = {
			default               = 70500,
		},
	},

	commshield_up3                        = {

		Smartshield               = true,
		Exteriorshield            = true,
		Visibleshield             = false,
		Visibleshieldrepulse      = false,
		ShieldStartingPower       = 23000,
		Shieldenergyuse           = 0,
		Shieldradius              = shieldradius,
		Shieldpower               = 28500,
		Shieldpowerregen          = 500,
		Shieldpowerregenenergy    = 0,
		rechargeDelay		  	  = 40,
		Shieldintercepttype       = 4,
		Shieldgoodcolor           = "0.0 0.2 1.0",
		Shieldbadcolor            = "1.0 0 0",
		Shieldalpha              = 0.2,

		texture1		          = "shield4",

		visibleShieldHitFrames    = 1,
		weaponType                = [[Shield]],
		damage                    = {
			default               = 1,
		},
	},

	commrailgun_up4               = {
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.5,
		commandfire               = true,
		-- cegtag					  = "burnblack",
		-- beamDecay                 = 0.9,
		beamtime				  = 0.5,
		beamttl                   = 10,
		largebeamlaser			  = true,
		laserFlareSize            = 6,
		sweepfire				  = false,
		duration                  = 0.8,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-large",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity BeamLaser",
		range                     = 900,
		reloadtime                = 30,
		WeaponType                = "BeamLaser",
		rgbColor                  = purple,
		rgbColor2                 = "0.25 0.25 0.25",
		soundTrigger              = true,
		soundstart                = "scifi_rifle_laser_B_single_01",
		-- soundHit                  = "explode5",
		-- sprayangle				  = 500,
		texture1                  = "lightning",
		texture2                  = "flash1",
		texture3                  = "flash1",
		texture4                  = "flash1",
		thickness                 = 16,
		tolerance                 = 500,
		turret                    = true,
		weaponVelocity            = 750,
		waterweapon				 = false,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                    = {
			default               = 240000,
		},
	},

	commshield_up4                        = {

		Smartshield               = true,
		Exteriorshield            = true,
		Visibleshield             = false,
		Visibleshieldrepulse      = false,
		ShieldStartingPower       = 28500,
		Shieldenergyuse           = 0,
		Shieldradius              = shieldradius,
		Shieldpower               = 42000,
		Shieldpowerregen          = 1000,
		Shieldpowerregenenergy    = 0,
		rechargeDelay		  	  = 20,
		Shieldintercepttype       = 4,
		Shieldgoodcolor           = "0.0 0.2 1.0",
		Shieldbadcolor            = "1.0 0 0",
		Shieldalpha              = 0.2,

		texture1		          = "shield4",

		visibleShieldHitFrames    = 1,
		weaponType                = [[Shield]],
		damage                    = {
			default               = 1,
		},
	},
}
