unitDef                    = {
	--mobileunit 
	transportbyenemy             = false; 
	--**
	buildCostEnergy              = 0,
	buildCostMetal               = buildCostMetal,
	buildDistance                = builddistance,
	builder                      = true,
	buildTime                    = 2.5,
	buildpic					 = buildpicture,
	capturable		             = false,
	CanAttack			         = true,
	CanAssist			         = true,
	canBeAssisted                = false,
	CanCapture                   = true,
	CanRepair			         = true,
	canRestore					 = true,

	cantBeTransported            = true,

	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canreclaim		             = true,
	canstop                      = true,
	category                     = "GROUND",
	description                  = [[Builds Units]],
	energyMake                   = 10,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = explodeas,
	footprintX                   = footprintx,
	footprintZ                   = footprintz,
	iconType                     = "commander",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	levelground                  = true,
	maxDamage                    = 1,
	maxSlope                     = 180,
	maxVelocity                  = maxvelocity,
	maxReverseVelocity           = 1,
	maxWaterDepth                = 5000,
	metalmake                    = 2,
	metalStorage                 = 0,
	movementClass                = movementclass,
	moveState			         = "0",
	name                         = humanname,
	noChaseCategories	         = "NOTAIR SUPPORT VTOL AMPHIB",
	objectName                   = objectname,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = selfdestructas,
	selfDestructCountdown         = 15,
	showPlayerName	             = true,
	showNanoSpray                = true,
	sightDistance                = 500,
	smoothAnim                   = true,
	stealth			             = true,
	seismicSignature             = 2,
	unitname                     = unitName,
	upright                      = false,
	workerTime                   = workertime,
	TerraformSpeed               = 2147000,
	--------------
	-- Movement --
	--------------
	acceleration 				 = 2,
	brakeRate                    = 0.1,
	turninplace 				 = true,
	turninplacespeedlimit 		 = 10,
	turnInPlaceAngleLimit		 = 45,
	turnrate 				 	 = 600,
	--------------
	--------------

	--------------------------
	-- Skillshot (aka DGun) --
	--------------------------
	noAutoFire                   = true,
	fireState                    = 0,
	canManualFire                = true,
	--------------------------
	--------------------------

	sfxtypes                     = {
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 
		
		explosiongenerators      = {
			"custom:nanoorb",
			"custom:emptydirt",
			"custom:burnblacksmall",
			"custom:gdhcannon",
		},
	},
	buildoptions                 = buildlist,
	sounds                       = {
		build					 = "miscfx/buildstart",
		underattack              = "units_under_attack",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = weapon1,
			badTargetCategory     = "BUILDING",
			onlyTargetCategory    = "GROUND BUILDING SHIP",
		},
	},
	customParams                 = {
		unittype				 = "mobile",
		unitrole				 = "Commander",
		area_mex_def			 = areamexdef,
		ProvideTech              = techprovided,
		RequireTech				 = techrequired,
		stockpileLimit           = 5,
		techlevel                = techlevel,
		--hpoverride               = hp,
		iscommander              = true,
		needed_cover             = 2,
		death_sounds             = "commander",
		factionname	             = "Loz Alliance",
		removeattack             = "true",

		nofriendlyfire	         = "1",
		normaltex               = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
	},
}

--------------------------------------------------------------------------------

weaponDefs                 = {
	commrailgun           = {
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		commandfire               = true,
		duration                  = 0.2,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity WaveLaser",
		range                     = 300,
		reloadtime                = 1,
		WeaponType                = "LaserCannon",
		rgbColor                  = blue,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "lozcommander-beam-short",
		soundHit                  = "phasegun1hit.wav",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 15,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 1000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= blue, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
		},
		damage                    = {
			default               = 30,
		},
	},

	commrailgun_up1               = {
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		commandfire               = true,
		duration                  = 0.2,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity WaveLaser",
		range                     = 400,
		reloadtime                = 1,
		WeaponType                = "LaserCannon",
		rgbColor                  = blue,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "lozcommander-beam-short",
		soundHit                  = "phasegun1hit.wav",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 15,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 1000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
		},
		damage                    = {
			default               = 400,
		},
	},

	commrailgun_up2               = {
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		commandfire               = true,
		duration                  = 0.2,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity WaveLaser",
		range                     = 600,
		reloadtime                = 2.5,
		WeaponType                = "LaserCannon",
		rgbColor                  = blue,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "lozcommander-beam-short",
		soundHit                  = "phasegun1hit.wav",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 15,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 1000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
		},
		damage                    = {
			default               = 6000,
		},
	},

	commrailgun_up3               = {
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		commandfire               = true,
		duration                  = 0.2,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity WaveLaser",
		range                     = 700,
		reloadtime                = 5,
		WeaponType                = "LaserCannon",
		rgbColor                  = blue,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "lozcommander-beam-short",
		soundHit                  = "phasegun1hit.wav",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 15,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 1000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
		},
		damage                    = {
			default               = 52500,
		},
	},

	commrailgun_up4               = {
		avoidGround               = false,
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.3,
		commandfire               = true,
		duration                  = 0.2,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-small",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity WaveLaser",
		range                     = 900,
		reloadtime                = 7.5,
		WeaponType                = "LaserCannon",
		rgbColor                  = blue,
		rgbColor2                 = "1 1 1",
		soundTrigger              = true,
		soundstart                = "lozcommander-beam-short",
		soundHit                  = "phasegun1hit.wav",
		-- sprayangle				  = 500,
		texture1                 = "wave",
		texture2                 = "empty",
		thickness                 = 15,
		tolerance                 = 1000,
		turret                    = true,
		weaponVelocity            = 1000,
		waterweapon				 = false,
		noexplode                 = true,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit            = "true",
		},
		damage                    = {
			default               = 196875,
		},
	},
}