unitDef                    = {
	acceleration            = 1,
	brakeRate               = 0.2,
	buildCostEnergy         = 0,
	buildCostMetal          = buildCostMetal,
	buildDistance           = buildDistance,
	builder                 = true,
	buildTime               = 5,
	buildpic                = buildpic,
	canAttack               = true,
	canGuard                = true,
	canHover                = true,
	canMove                 = true,
	canPatrol               = true,
	CanAssist               = true,
	canBeAssisted           = true,
	CanCapture              = false,
	CanRepair               = true,
	canRestore              = true,
	canBuild                = true,
	canGuard                = true,
	canHover                = true,
	canMove                 = true,
	canPatrol               = true,
	canreclaim              = true,
	category                = "GROUND",
	description             = [[Builds Units]],
	energyMake              = 0,
	energyStorage           = 0,
	energyUse               = 0,
	explodeAs               = explodeAs,
	footprintX              = footprintx,
	footprintZ              = footprintz,
	iconType                = "engineer",
	idleAutoHeal            = .5,
	idleTime                = 2200,
	leaveTracks             = false,
	maxDamage               = maxDamage,
	maxVelocity             = 4.5,
	maxReverseVelocity      = 1,
	maxWaterDepth           = 10,
	metalStorage            = 0,
	movementClass           = movementclass,
	name                    = humanName,
	noChaseCategory         = "VTOL",
	objectName              = objectName,
	script                  = script,
	radarDistance           = 0,
	repairable              = false,
	selfDestructAs          = explodeAs,
	showNanoSpray           = false,
	sightDistance           = 500,
	smoothAnim              = true,
	stealth                 = true,
	seismicSignature        = 2,
	transportbyenemy        = false;
	--turnInPlace           = false,
	--turnInPlaceSpeedLimit = 2.3,
	turnInPlace             = true,
	turnRate                = 5000,
	--turnrate              = 250,
	unitname                = unitName,
	workerTime              = workertime,
	capturespeed            = 1,
	TerraformSpeed          = 2147000,
	ReclaimSpeed            = 0,
	repairspeed             = 0.5,
	sfxtypes                = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:nanoorb",
			"custom:emptydirt",
			"custom:blacksmoke",
		},
	},
	buildoptions = lozt1buildlist,
	sounds       = {
		underattack = "other/unitsunderattack1",
		ok          = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	customParams                 = {
		unittype         = "mobile",
		unitrole		 = "Builder",
		area_mex_def     = areamexdef,
		requiretech      = requiretech,
		supply_cost      = 1,
		canbetransported = "true",
		death_sounds     = "generic",
		nofriendlyfire   = "1",
		noenergycost     = false,
		normaltex        = "unittextures/lego2skin_explorernormal.dds",
		buckettex        = "unittextures/lego2skin_explorerbucket.dds",
		factionname      = "Loz Alliance",
	},
}