unitDef                    = {

	acceleration                 = 0.18,
	brakeRate                    = 1,
	buildCostEnergy              = 0,
	buildCostMetal               = 40000,
	builder                      = false,
	buildTime                    = 5,
	buildpic					 = "fedanarchid.png",
	canAttack                    = true,
	
	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = "1",
	cantBeTransported            = true,
	category                     = "ARMORED NOTAIR SKIRMISHER",
	
	description                  = [[Endbringer Class Obliteration Strider]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = explodeAs,
	firestandorders              = "1",
	footprintX                   = 16,
	footprintZ                   = 16,
	iconType                     = "anarchid",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	leaveTracks                  = false,
	maxDamage                    = 20000,
	maxVelocity                  = 1.5,
	maxReverseVelocity           = 1,
	maxWaterDepth                = 80,
	metalStorage                 = 0,
	movementClass                = "WALKERTANK16",
	name                         = humanName,
	noChaseCategory              = "VTOL",
	objectName                   = objectName,
	script	                     = script,
	pushResistant		         = true,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = explodeAs,
	sightDistance                = 2000,
	smoothAnim                   = true,
	stealth			             = true,
	seismicSignature             = 4,
	transportbyenemy             = false;
	turnInPlace                  = true,
	turnRate                     = 5000,
	unitname                     = unitName,
	upright                      = false,
	--  usePieceCollisionVolumes = true,

	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:gdhcannon",
			"custom:emptydirt",
			"custom:flamethrowerrange750",
			"custom:blacksmoke",
			"custom:burnblack",
		},
	},
	sounds                       = {
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = "heavybeamweapon",
		},
		[2]                      = {
			def                  = "particlebeamcannon",
		},
		[3]                      = {
			def                  = "particlebeamcannon",
		},
	},
	customParams                 = {
		unittype				  = "mobile",
		unitrole				 = "Assault",
		death_sounds             = "nuke",
		RequireTech              = tech,
		normaltex               = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		factionname	             = "Federation of Kala",
		corpse                   = "energycore",
	},
}

weaponDefs                 = {
	heavybeamweapon              = {
		AreaOfEffect             = 10,
		avoidFriendly            = false,
		avoidFeature             = false,
		collideFriendly          = false,
		collideFeature           = false,
		beamTime                 = 1,
		largebeamlaser			 = true,
		cameraShake		         = 1,
		coreThickness            = 0.2,
		--	cegTag               = "mediumcannonweapon3",
		--    duration           = 0.2,
		energypershot            = 0,
		explosionGenerator       = "custom:genericshellexplosion-large-sparks-burn",
		fallOffRate              = 0,
		fireStarter              = 50,
		impulseFactor            = 0,
		interceptedByShieldType  = 4,
		minintensity             = "1",
		name                     = "Laser",
		range                    = 2000,
		reloadtime               = 1,
		WeaponType               = "BeamLaser",
		rgbColor                 = "1 0 0",
		rgbColor2                = "1 1 1",
		soundTrigger             = true,
		soundstart               = "weapons/krabprimary.wav",
		--    soundHit           = "explosions/mediumcannonhit.wav",
		--	sweepfire		     = true,
		texture1                 = "lightning",
		texture2                 = "laserend",
		thickness                = 12,
		tolerance                = 1000,
		turret                   = true,
		weaponVelocity           = 800,
		customparams             = {
		},
		damage                   = {
			default              = 6000,
		},
	},
	
	particlebeamcannon                 = {
		
		accuracy                 = 0,
		AreaOfEffect             = 10,
		avoidFeature             = false,
		avoidFriendly            = false,
		collideFeature           = false,
		collideFriendly          = false,
		explosionGenerator       = "custom:burnblack",
		coreThickness            = 0.1,
		duration                 = 0.8,
		energypershot            = 0,
		fallOffRate              = 0.1,
		fireStarter              = 50,
		interceptedByShieldType  = 4,
		soundstart               = "weapons/Bio gun Shot 6.wav",
		
		minintensity             = 1,
		impulseFactor            = 0,
		name                     = "Something with Flames",
		range                    = 2000,
		reloadtime               = 0.2,
		WeaponType               = [[LaserCannon]],
		rgbColor                 = "1 0.5 0",
		rgbColor2                = "1 1 1",
		thickness                = 2,
		tolerance                = 1000,
		turret                   = true,
		texture1                 = "shot",
		texture2                 = "empty",
		weaponVelocity           = 1000,
		sprayangle				 = 500,
		customparams             = {
		},      
		damage                   = {
			default              = 20,
		},
	},
}
