local unitHeat = 0.0042
if Spring.GetModOptions and Spring.GetModOptions().unitheat ~= nil then
	unitHeat = Spring.GetModOptions().unitheat * 0.0042
end

local flowMappingToggle = true
local allowRawMovement = true

-- In Degrees
local allterrainslopetolerance = 100
local walkerslopetolerance = 45
local wheeledslopetolerance = 30

-- Fix the numbers for springs fucking stupid magic numbers
allterrainslopetolerance = allterrainslopetolerance / 1.5
walkerslopetolerance = walkerslopetolerance / 1.5
wheeledslopetolerance = wheeledslopetolerance / 1.5

local minWaterDepth = 5

local genericDepthmodParams = {
		minHeight      = 0,
		maxHeight      = 500,
		maxScale       = 3,
		quadraticCoeff = 0,
		linearCoeff    = 0, -- deprecates "depthMod"
		constantCoeff  = 2,
}

local amphibDepthmodParams = {
		minHeight      = 0,
		maxHeight      = 500,
		maxScale       = 1.5,
		quadraticCoeff = 0,
		linearCoeff    = 0, -- deprecates "depthMod"
		constantCoeff  = 2,
}

local submarineDepthmodParams = {
    minHeight      = 0,
    maxHeight      = 5000,
    maxScale       = 1.5,
    quadraticCoeff = 0,
    linearCoeff    = 0, -- deprecates "depthMod"
    constantCoeff  = 2,
}

local moveDefs = {

-- Walkers
    WALKERTANK2 = {
        footprintx=2,
        footprintz=2,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK3 = {
        footprintx=3,
        footprintz=3,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK4 = {
        footprintx=4,
        footprintz=4,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK5 = {
        footprintx=5,
        footprintz=5,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK6 = {
        footprintx=6,
        footprintz=6,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK7 = {
        footprintx=7,
        footprintz=7,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK8 = {
        footprintx=8,
        footprintz=8,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK9 = {
        footprintx=9,
        footprintz=9,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK10 = {
        footprintx=10,
        footprintz=10,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK11 = {
        footprintx=11,
        footprintz=11,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK12 = {
        footprintx=12,
        footprintz=12,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK13 = {
        footprintx=13,
        footprintz=13,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK14 = {
        footprintx=14,
        footprintz=14,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK15 = {
        footprintx=15,
        footprintz=15,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WALKERTANK16 = {
        footprintx=16,
        footprintz=16,
        maxslope=walkerslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },

    ----------------------------------------------------------------------------------------------------------------------------------------------------------------
    ------------------------------------------------------------------------------------------------------------------------------------------------------------------

    -- Wheeled/Tracked Tanks
    WHEELEDTANK2 = {
        footprintx=2,
        footprintz=2,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK3 = {
        footprintx=3,
        footprintz=3,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK4 = {
        footprintx=4,
        footprintz=4,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK5 = {
        footprintx=5,
        footprintz=5,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK6 = {
        footprintx=6,
        footprintz=6,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK7 = {
        footprintx=7,
        footprintz=7,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK8 = {
        footprintx=8,
        footprintz=8,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK9 = {
        footprintx=9,
        footprintz=9,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK10 = {
        footprintx=10,
        footprintz=10,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK11 = {
        footprintx=11,
        footprintz=11,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK12 = {
        footprintx=12,
        footprintz=12,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK13 = {
        footprintx=13,
        footprintz=13,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK14 = {
        footprintx=14,
        footprintz=14,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK15 = {
        footprintx=15,
        footprintz=15,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    WHEELEDTANK16 = {
        footprintx=16,
        footprintz=16,
        maxslope=wheeledslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=40,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },

    ALLTERRAINTANK2 = {
        footprintx=2,
        footprintz=2,
        maxslope=allterrainslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=allterrainslopetolerance,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    ALLTERRAINTANK4 = {
        footprintx=4,
        footprintz=4,
        maxslope=allterrainslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=allterrainslopetolerance,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },
    ALLTERRAINTANK8 = {
        footprintx=8,
        footprintz=8,
        maxslope=allterrainslopetolerance,
        maxwaterdepth=250,
        maxwaterslope=allterrainslopetolerance,
        badwaterslope=40,
        crushstrength=20,
        depthModParams = genericDepthmodParams,
        minwaterdepth=10,
        heatmod=unitHeat,
        slopemod=3,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },

-- Submarines
--    SUBMARINE4 = {
--        submarine = true,
--        speedModClass=3,
--        footprintx=4,
--        footprintz=4,
--        maxslope=60,
--        maxwaterslope=60,
--        badwaterslope=0,
--        crushstrength=20,
--        minwaterdepth=40,
--        heatmod=unitHeat,
--        slopemod=0,
--        allowRawMovement=allowRawMovement,
--        flowMapping=flowMappingToggle,
--    },
--
--    SUBMARINE5 = {
--        submarine = true,
--        speedModClass=3,
--        footprintx=5,
--        footprintz=5,
--        maxslope=60,
--        maxwaterslope=60,
--        badwaterslope=0,
--        crushstrength=20,
--        minwaterdepth=40,
--        heatmod=unitHeat,
--        slopemod=0,
--        allowRawMovement=allowRawMovement,
--        flowMapping=flowMappingToggle,
--    },

    -- Ships
    SHIP3 = {
        submarine = false,
        speedModClass=3,
        footprintx=3,
        footprintz=3,
        maxslope=60,
        maxwaterslope=60,
        badwaterslope=0,
        crushstrength=20,
        minwaterdepth=minWaterDepth,
        heatmod=unitHeat,
        slopemod=0,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },

    SHIP4 = {
        submarine = false,
        speedModClass=3,
        footprintx=4,
        footprintz=4,
        maxslope=60,
        maxwaterslope=60,
        badwaterslope=0,
        crushstrength=20,
        minwaterdepth=minWaterDepth,
        heatmod=unitHeat,
        slopemod=0,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },

    SHIP5 = {
        submarine = false,
        speedModClass=3,
        footprintx=5,
        footprintz=5,
        maxslope=60,
        maxwaterslope=60,
        badwaterslope=0,
        crushstrength=20,
        minwaterdepth=minWaterDepth,
        heatmod=unitHeat,
        slopemod=0,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },

    SHIP7 = {
        submarine = false,
        speedModClass=3,
        footprintx=7,
        footprintz=7,
        maxslope=60,
        maxwaterslope=60,
        badwaterslope=0,
        crushstrength=20,
        minwaterdepth=minWaterDepth,
        heatmod=unitHeat,
        slopemod=0,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },

    SHIP8 = {
        submarine = false,
        speedModClass=3,
        footprintx=8,
        footprintz=8,
        maxslope=60,
        maxwaterslope=60,
        badwaterslope=0,
        crushstrength=20,
        minwaterdepth=minWaterDepth,
        heatmod=unitHeat,
        slopemod=0,
        allowRawMovement=allowRawMovement,
        flowMapping=flowMappingToggle,
    },

}

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

-- convert from map format to the expected array format

local array = {}
local i = 1
for k,v in pairs(moveDefs) do
	v.heatmapping = false -- disable heatmapping
	v.allowRawMovement = true
	array[i] = v
	v.name = k
	i = i + 1
end


--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

return array

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------