-----------------------------
-----------------------------
--Buildlists for factories

Shared.buildListf1landfac = {
	[[fedak]],
	[[fedstorm]],
	[[fedthud]],
	[[fedcrasher]],
	[[fedbear]],
	[[fedcobra]],
	[[fedavalanche]],
	[[fedphalanx]],
	[[fedgoliath]],
	[[fedjuggernaut]],
	[[fedengineer]],
	[[fedengineer_up1]],
	[[fedengineer_up2]],
	[[fedengineer_up3]],
}

Shared.buildListFedAirPlant = {
	[[airscout]],
	[[fedsparrow]],
	[[fedcrow]],
	[[fedhawk]],
	[[fedcondor]],
	[[fedeagle]],
}

Shared.buildListFedSeaPlant = {
	[[fedcrusader]],
	[[fedpiranha]],
	[[fedcolossus]],
	[[fedconqueror]],
}

Shared.buildListf2landfac = {
	[[lozflea]],
	[[lozdiamondback]],
	[[lozroach]],
	[[lozscorpion]],
	[[lozreaper]],
	[[lozluger]],
	[[lozpulverizer]],
	[[lozmammoth]],
	[[lozsilverback]],
	[[lozengineer]],
	[[lozengineer_up1]],
	[[lozengineer_up2]],
	[[lozengineer_up3]],
}

Shared.buildListLozAirPlant = {
	[[airscout]],
	[[lozwasp]],
	[[lozbumblebee]],
	[[lozdragonfly]],
	[[lozhornet]],
	[[lozcrane]],
	[[loztitan]],
}

Shared.buildListLozSeaPlant = {
	[[lozenforcer]],
	[[lozsnake]],
	[[lozexecutioner]],
	[[lozwarlord]],
}

-----------------------------
-----------------------------
--Buildlists for mobile builders

Shared.buildListFedt0 = {
	-- [[f1landfac]],
	-- [[fedairplant]],
	-- [[fedseaplant]],
	[[metalextractor]],
	[[fissionpowerplant]],
	-- [[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	-- [[mediumsupplydepot]],
	-- [[mediumstorage]],
	-- [[largestorage]],
	-- [[cloakingtower]],
	-- [[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	-- [[fedmenlo]],
	-- [[fedstinger]],
	-- [[fedearthquakemine]],
	-- [[fedimmolator]],
	-- [[fedjavelin]],
	-- [[fedguardian]],
	-- [[fedbertha]],
	-- [[healstation]],
	-- [[fedanarchid]],
	[[fedengineer]],
}

Shared.buildListFedt1 = {
	[[f1landfac]],
	[[fedairplant]],
	[[fedseaplant]],
	[[metalextractor_up1]],
	[[fissionpowerplant]],
	-- [[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	-- [[mediumsupplydepot]],
	-- [[mediumstorage]],
	-- [[largestorage]],
	-- [[cloakingtower]],
	-- [[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	[[fedmenlo]],
	[[fedstinger]],
	[[fedearthquakemine]],
	-- [[fedimmolator]],
	-- [[fedjavelin]],
	-- [[fedguardian]],
	-- [[fedbertha]],
	-- [[healstation]],
	-- [[fedanarchid]],
	[[fedengineer_up1]],
}

Shared.buildListFedt2 = {
	[[f1landfac]],
	[[fedairplant]],
	[[fedseaplant]],
	[[metalextractor_up2]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	-- [[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	[[fedmenlo]],
	[[fedstinger]],
	[[fedearthquakemine]],
	[[fedimmolator]],
	[[fedjavelin]],
	-- [[fedguardian]],
	-- [[fedbertha]],
	[[healstation]],
	-- [[fedanarchid]],
	[[fedengineer_up2]],
}

Shared.buildListFedt3 = {
	[[f1landfac]],
	[[fedairplant]],
	[[fedseaplant]],
	[[metalextractor_up3]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	[[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	[[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	[[largeshieldgenerator]],
	[[fedmenlo]],
	[[fedstinger]],
	[[fedearthquakemine]],
	[[fedimmolator]],
	[[fedjavelin]],
	[[fedguardian]],
	[[fedbertha]],
	[[healstation]],
	-- [[fedanarchid]],
	[[fedengineer_up3]],
}

Shared.buildListFedt4 = {
	[[f1landfac]],
	[[fedairplant]],
	[[fedseaplant]],
	[[metalextractor_up3]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	[[coldfusionpowerplant]],
	[[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	[[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	[[largeshieldgenerator]],
	[[fedmenlo]],
	[[fedstinger]],
	[[fedearthquakemine]],
	[[fedimmolator]],
	[[fedjavelin]],
	[[fedguardian]],
	[[fedbertha]],
	[[healstation]],
	[[fedanarchid]],
	[[fedengineer_up3]],
}

Shared.buildListLoz = {
}

Shared.buildListLozt0 = {
	-- [[f2landfac]],
	-- [[lozairplant]],
	-- [[lozseaplant]],
	[[metalextractor]],
	[[fissionpowerplant]],
	-- [[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	-- [[mediumsupplydepot]],
	-- [[mediumstorage]],
	-- [[largestorage]],
	-- [[cloakingtower]],
	-- [[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	-- [[lozjericho]],
	-- [[lozrazor]],
	-- [[lozinferno]],
	-- [[lozrattlesnake]],
	-- [[lozannihilator]],
	-- [[lozintimidator]],
	-- [[healstation]],
	-- [[lozeurypterid]],
	[[lozengineer]],
}

Shared.buildListLozt1 = {
	[[f2landfac]],
	[[lozairplant]],
	[[lozseaplant]],
	[[metalextractor_up1]],
	[[fissionpowerplant]],
	-- [[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	-- [[mediumsupplydepot]],
	-- [[mediumstorage]],
	-- [[largestorage]],
	-- [[cloakingtower]],
	-- [[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	[[lozjericho]],
	[[lozrazor]],
	-- [[lozinferno]],
	-- [[lozrattlesnake]],
	-- [[lozannihilator]],
	-- [[lozintimidator]],
	-- [[healstation]],
	-- [[lozeurypterid]],
	[[lozengineer_up1]],
}

Shared.buildListLozt2 = {
	[[f2landfac]],
	[[lozairplant]],
	[[lozseaplant]],
	[[metalextractor_up2]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	-- [[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	[[lozjericho]],
	[[lozrazor]],
	[[lozinferno]],
	[[lozrattlesnake]],
	-- [[lozannihilator]],
	-- [[lozintimidator]],
	[[healstation]],
	-- [[lozeurypterid]],
	[[lozengineer_up2]],
}

Shared.buildListLozt3 = {
	[[f2landfac]],
	[[lozairplant]],
	[[lozseaplant]],
	[[metalextractor_up3]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	[[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	[[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	[[largeshieldgenerator]],
	[[lozjericho]],
	[[lozrazor]],
	[[lozinferno]],
	[[lozrattlesnake]],
	[[lozannihilator]],
	[[lozintimidator]],
	[[healstation]],
	-- [[lozeurypterid]],
	[[lozengineer_up3]],
}

Shared.buildListLozt4 = {
	[[f2landfac]],
	[[lozairplant]],
	[[lozseaplant]],
	[[metalextractor_up3]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	[[coldfusionpowerplant]],
	[[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	[[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	[[largeshieldgenerator]],
	[[lozjericho]],
	[[lozrazor]],
	[[lozinferno]],
	[[lozrattlesnake]],
	[[lozannihilator]],
	[[lozintimidator]],
	[[healstation]],
	[[lozeurypterid]],
	[[lozengineer_up3]],
}


-----------------------------
-----------------------------
--Buildlists for SimpleAI Commanders

Shared.buildListFedt0_ai = {
	-- [[f1landfac]],
	-- [[fedairplant]],
	-- [[fedseaplant]],
	[[metalextractor]],
	[[fissionpowerplant]],
	-- [[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	-- [[mediumsupplydepot]],
	-- [[mediumstorage]],
	-- [[largestorage]],
	-- [[cloakingtower]],
	-- [[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	-- [[fedmenlo]],
	-- [[fedstinger]],
	-- [[fedearthquakemine]],
	-- [[fedimmolator]],
	-- [[fedjavelin]],
	-- [[fedguardian]],
	-- [[fedbertha]],
	-- [[healstation]],
	-- [[fedanarchid]],
	[[fedengineer]],
	[[fedcommander_up1_ai]],
}

Shared.buildListFedt1_ai = {
	[[f1landfac]],
	[[fedairplant]],
	[[fedseaplant]],
	[[metalextractor_up1]],
	[[fissionpowerplant]],
	-- [[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	-- [[mediumsupplydepot]],
	-- [[mediumstorage]],
	-- [[largestorage]],
	-- [[cloakingtower]],
	-- [[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	[[fedmenlo]],
	[[fedstinger]],
	[[fedearthquakemine]],
	-- [[fedimmolator]],
	-- [[fedjavelin]],
	-- [[fedguardian]],
	-- [[fedbertha]],
	-- [[healstation]],
	-- [[fedanarchid]],
	[[fedengineer_up1]],
	[[fedcommander_up2_ai]],
}

Shared.buildListFedt2_ai = {
	[[f1landfac]],
	[[fedairplant]],
	[[fedseaplant]],
	[[metalextractor_up2]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	-- [[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	-- [[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	-- [[largeshieldgenerator]],
	[[fedmenlo]],
	[[fedstinger]],
	[[fedearthquakemine]],
	[[fedimmolator]],
	[[fedjavelin]],
	-- [[fedguardian]],
	-- [[fedbertha]],
	[[healstation]],
	-- [[fedanarchid]],
	[[fedengineer_up2]],
	[[fedcommander_up3_ai]],
}

Shared.buildListFedt3_ai = {
	[[f1landfac]],
	[[fedairplant]],
	[[fedseaplant]],
	[[metalextractor_up3]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	[[coldfusionpowerplant]],
	-- [[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	[[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	[[largeshieldgenerator]],
	[[fedmenlo]],
	[[fedstinger]],
	[[fedearthquakemine]],
	[[fedimmolator]],
	[[fedjavelin]],
	[[fedguardian]],
	[[fedbertha]],
	[[healstation]],
	-- [[fedanarchid]],
	[[fedengineer_up3]],
	[[fedcommander_up4_ai]],
}

Shared.buildListFedt4_ai = {
	[[f1landfac]],
	[[fedairplant]],
	[[fedseaplant]],
	[[metalextractor_up3]],
	[[fissionpowerplant]],
	[[fusionpowerplant]],
	[[coldfusionpowerplant]],
	[[blackholepowerplant]],
	[[supplydepot]],
	[[mediumsupplydepot]],
	[[mediumstorage]],
	[[largestorage]],
	[[cloakingtower]],
	[[smallshieldgenerator]],
	[[largeshieldgenerator]],
	[[fedmenlo]],
	[[fedstinger]],
	[[fedearthquakemine]],
	[[fedimmolator]],
	[[fedjavelin]],
	[[fedguardian]],
	[[fedbertha]],
	[[healstation]],
	[[fedanarchid]],
	[[fedengineer_up3]],
}
--[[
Shared.buildListTurret = {}
for i = 1, #Shared.buildList do
	Shared.buildListTurret[i] = Shared.buildList[i]
end
for i = 1, #turrets do
	Shared.buildListTurret[#Shared.buildListTurret + 1] = turrets[i]
end

local factory = {

}

Shared.buildListFactory = {}
for i = 1, #Shared.buildList do
	Shared.buildListFactory[i] = Shared.buildList[i]
end
for i = 1, #factory do
	Shared.buildListFactory[#Shared.buildListFactory + 1] = factory[i]
end
]]--