unitDef                    = {
	acceleration                 = 0.18,
	brakeRate                    = 0.2,
	buildCostEnergy              = 0,
	buildCostMetal               = 45000,
	builder                      = false,
	buildTime                    = 5,
	buildpic					 = "lozjaguar.png",
	canAttack                    = true,
	
	canGuard                     = true,
	canHover                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = "1",
	category                     = "ARMORED NOTAIR SUPPORT",
	description                  = [[Endbringer Class Nuclear Battle Tank]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = explodeAs,
	footprintX                   = 6,
	footprintZ                   = 6,
	--highTrajectory               = 1,
	iconType                     = "lacerator",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	leaveTracks                  = false,
	maxDamage                    = 20000,
	maxVelocity                  = 1.3,
	maxReverseVelocity           = 0.25,
	maxWaterDepth                = 20,
	metalStorage                 = 0,
	movementClass                = "WHEELEDTANK16",
	noChaseCategory              = "VTOL",
	name                         = humanName,
	objectName                   = objectName,
	script						 = script,
	pushResistant		         = true,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = explodeAs,
	side                         = "CORE",
	sightDistance                = 3500,
	smoothAnim                   = true,
	stealth			             = true,
	seismicSignature             = 4,
	transportbyenemy             = false;
	turnInPlace                  = true,
	turnRate                     = 5000,
	unitname                     = unitName,
	workerTime                   = 0,
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:gdhcannon",
			"custom:emptydirt",
			"custom:blacksmoke",
		},
	},
	sounds                       = {
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = "nukeartyweapon",
		},
	},
	customParams                 = {
		unittype				  = "mobile",
		unitrole				 = "Assault",
		death_sounds             = "nuke",
		RequireTech              = tech,
		normaltex               = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		factionname	             = "Loz Alliance",
		corpse                   = "energycore",
	},
}

weaponDefs                 = {
	nukeartyweapon               = {
		AreaOfEffect             = 1250,
		avoidFriendly            = false,
		avoidFeature             = false,
		collideFriendly          = false,
		collideFeature           = false,
		
		cegTag                   = "nukeartyshot",
		explosionGenerator       = "custom:NUKEDATBEWMSMALL",
		edgeEffectiveness        = 0.1,
		energypershot            = 0,
		highTrajectory			 = 0,
		impulseFactor            = 0,
		interceptedByShieldType  = 4,
		name                     = "Light Cannon",
		range                    = 3500,
		reloadtime               = 15,
		size					 = 16,
		weaponType		         = "Cannon",
		soundHit                 = "deathsounds/nuke/nuke1.wav",
		soundStart               = "weapons/nukeartyshot.wav",
		
		tolerance                = 2000,
		turret                   = true,
		weaponVelocity           = 800,
		customparams             = {
		}, 
		damage                   = {
			default              = 30000,
		},
	},
}
