unitDef                     = {
	buildAngle                    = 8192,
	buildCostEnergy               = 0,
	buildCostMetal                = 7000,
	builder                       = false,
	buildTime                     = 5,
	buildpic					  = "eheavyturret2.png",
	canAttack                     = true,
	canstop                       = "1",
	category                      = "BUILDING",
	description                   = [[Heavy Plasma Battery (Anti-Armor)]],
	energyStorage                 = 0,
	energyUse                     = 0,
	explodeAs                     = "hugeBuildingExplosionGenericRed",
	footprintX                    = 6,
	footprintZ                    = 6,
	floater			              = false,
	idleAutoHeal                  = .5,
	idleTime                      = 2200,
	iconType                      = "structuredefenset3",
	maxDamage                     = 1200,
	maxSlope                      = 60,
	maxWaterDepth                 = 0,
	metalStorage                  = 0,
	name                          = humanName,
	objectName                    = objectName,
	script						  = script,
	radarDistance                 = 0,
	repairable		              = false,
	selfDestructAs                = "hugeBuildingExplosionGenericRed",
	side                          = "CORE",
	sightDistance                 = 1000,
	smoothAnim                    = true,
	unitname                      = unitName,
	workerTime                    = 0,
	yardMap                       = "oooooo oooooo oooooo oooooo oooooo oooooo",

	sfxtypes                      = { 
		pieceExplosionGenerators  = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators       = {
			"custom:gdhcannon",
			"custom:needspower",
			"custom:burnblack",
		},
	},
	sounds                        = {
		underattack               = "units_under_attack",
		select                    = {
			"other/turretselect",
		},
	},
	weapons                       = {
		[1]                       = {
			def                   = "plasmacannon",
			badTargetCategory     = "BUILDING GROUND SHIP",
			onlyTargetCategory    = "MASSIVE GROUND BUILDING SHIP",
		},
	},
	customParams                  = {
		unittype				  = "building",
		unitrole				  = "Special Turret",
		unitrole_sound            = "turret",
		needed_cover              = 5,
		--supply_cost               = supply,
		RequireTech				  = tech,
		death_sounds              = "generic",
		normaltex                 = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                 = "unittextures/lego2skin_explorerbucket.dds",
		factionname	              = "Federation of Kala",
		

		-- Begin unit rings
		ring_color = "1,0,0,0.5",
		ring_radius = "1200",
		ring_linewidth = "1",
		ring_divs = "128",
		ring_alwaysshow = "false",
	},
	useGroundDecal                = true,
	BuildingGroundDecalType       = "factorygroundplate.dds",
	BuildingGroundDecalSizeX      = 8,
	BuildingGroundDecalSizeY      = 8,
	BuildingGroundDecalDecaySpeed = 0.9,
}

weaponDefs                  = {
	plasmacannon                	= {
		AreaOfEffect           = 250,
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		--cegTag			   = "thudshot",
		edgeEffectiveness	   = 0.1,
		explosionGenerator     = "custom:genericshellexplosion-large",
		energypershot          = 0,
		--duration			   = 0.25,
		-- highTrajectory		   = 1,
		impulseFactor          = 0,
		interceptedByShieldType  = 4,
		model                   = "projectile/projectileorange1-5x.s3o",
		name                   = "Plasma Cannon",
		--noExplode			   = true,
		range                  = 1200,
		reloadtime             = 8,
		size				   = 16,
		projectiles			   = 1,
		weaponType		       = "Cannon",
		soundStart             = "guardian-single-shot",
		soundHit	           = "mediumcannonhit",
		soundTrigger           = true,
		--sprayAngle             = 1250,
		tolerance              = 8000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 400,
		customparams             = {
			expl_light_color	= orange, -- As a string, RGB
			expl_light_radius	= hugeExplosion, -- In Elmos
			expl_light_life		= hugeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                   = {
			default              = 3500,
		},
	},
}