unitDef                    = {

	--mobileunit 
	transportbyenemy             = false; 
	--**
	buildCostEnergy              = 500,
	buildCostMetal               = buildcostmetal,
	buildDistance                = builddistance,
	builder                      = true,
	buildTime                    = 2.5,
	buildpic					 = buildpicture,
	capturable		             = false,
	CanAttack			         = true,
	CanAssist			         = true,
	canBeAssisted                = true,
	CanCapture                   = true,
	CanRepair			         = true,
	canRestore					 = true,

	cantBeTransported            = true,
	
	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canreclaim		             = true,
	canstop                      = true,
	category                     = "GROUND",
	description                  = [[Builds Units]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = explodeas,
	footprintX                   = footprintx,
	footprintZ                   = footprintz,
	
	iconType                     = "commander",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	autoHeal                     = 0,
	levelground                  = true,
	maxDamage                    = 1,
	maxSlope                     = 180,
	maxVelocity                  = maxvelocity,
	maxReverseVelocity           = 1,
	maxWaterDepth                = 5000,
	metalmake                    = 0,
	metalStorage                 = 0,
	movementClass                = movementclass,
	moveState			         = "0",
	name                         = humanname,
	noChaseCategories	         = "NOTAIR SUPPORT VTOL AMPHIB",
	objectName                   = objectname,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = selfdestructas,
	selfDestructCountdown         = 15,
	showPlayerName	             = true,
	showNanoSpray                = true,
	sightDistance                = 500,
	smoothAnim                   = true,
	stealth			             = true,
	seismicSignature             = 2,
	unitname                     = unitName,
	upright                      = false,
	workerTime                   = workertime,
	TerraformSpeed               = 2147000,
	--------------
	-- Movement --
	--------------
	acceleration 				 = 2,
	brakeRate                    = 0.1,
	turninplace 				 = true,
	turninplacespeedlimit 		 = 10,
	turnInPlaceAngleLimit		 = 45,
	turnrate 				 	 = 750,
	--------------
	--------------


	sfxtypes                     = {
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 
		
		explosiongenerators      = {
			"custom:nanoorb",
			"custom:emptydirt",
			"custom:blacksmoke",
			"custom:gdhcannon",
		},
	},
	buildoptions                 = buildlist,
	sounds                       = {
		build					 = "miscfx/buildstart",
		underattack              = "units_under_attack",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = weapon1,
			badTargetCategory     = "BUILDING",
			onlyTargetCategory    = "GROUND BUILDING SHIP",
		},
	},
	customParams                 = {
		unitguide = [[The Federation Commander is the player's starting unit and the foundation of every match. It builds all structures, repairs friendly units, reclaims wreckage, and captures enemy buildings, while its EMG Disruption Cannon provides a meaningful self-defense option that stacks impairment on anything it hits. The Commander upgrades through four tiers alongside overall tech progression, gaining range and dramatically increased weapon damage at each step — by Tier 4 a single hit from its cannon is a serious statement. Losing the Commander ends the game; protecting it while using it aggressively is the central tension of every match.]],
		unittype				 = "mobile",
		unitrole 				 = "Commander",
		area_mex_def			 = areamexdef,
		ProvideTech              = techprovided,
		RequireTech				 = techrequired,
		stockpileLimit           = 5,
		techlevel                = techlevel,
		iscommander              = true,
		needed_cover             = 2,
		death_sounds             = "commander",
		factionname	             = "Federation of Kala",
		--removeattack             = "true",
		--removerepair             = "true",
		--hpoverride               = hp,
		buildcostenergyoverride  = buildCostEnergy,
		nofriendlyfire	         = "1",
		normaltex               = "unittextures/lego2skin_explorernormal.dds",
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
	},
}

--------------------------------------------------------------------------------

weaponDefs                 = {
	particlebeamcannon                 = {
		areaofeffect           = 50,
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		cegTag                 = "railgun",
		rgbColor               = "1 0 0",
		rgbColor2              = "1 1 1",
		explosionGenerator     = "custom:genericshellexplosion-medium-sparks-burn",
		edgeEffectiveness	   = 1,
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.25,
		impulseFactor          = 0,
		--interceptedByShieldType  = 4,
		name                   = "E.M.G. Disruption Cannon",
		range                  = 550,
		reloadtime             = 1,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "disruption-laser",
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.6,
		thickness              = 6,
		tolerance              = 10000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 1500,
		customparams             = {
			expl_light_color	= red, -- As a string, RGB
			expl_light_radius	= smallExplosion, -- In Elmos
			expl_light_life		= smallExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit          = "true",
			disruptionweapon    = 1,
			weaponguide = [[Disruption weapons deal no direct damage, instead building disruptive interference within the target's systems. As disruption accumulates, the target's movement degrades progressively — and so does its ability to perceive the battlefield. At full disruption, the target is locked out entirely: immobilized, nearly blind, and unable to fire for several seconds. Disruption also arcs to nearby enemies on impact, making these weapons particularly effective against clustered formations. Continued fire on a locked-out target is not wasted — the arc still spreads to those around it.]],
		},
		damage                   = {
			default              = 70,
		},
	},

	particlebeamcannon_up1                 = {
		areaofeffect           = 50,
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		cegTag                 = "railgun",
		rgbColor               = "1 0 0",
		rgbColor2              = "1 1 1",
		explosionGenerator     = "custom:genericshellexplosion-medium-sparks-burn",
		edgeEffectiveness	   = 1,
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.25,
		impulseFactor          = 0,
		--interceptedByShieldType  = 4,
		name                   = "E.M.G. Disruption Cannon",
		range                  = 600,
		reloadtime             = 1,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "disruption-laser",
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.6,
		thickness              = 6,
		tolerance              = 10000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 1500,
		customparams             = {
			expl_light_color	= red, -- As a string, RGB
			expl_light_radius	= smallExplosion, -- In Elmos
			expl_light_life		= smallExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit          = "true",
			disruptionweapon    = 1,
			weaponguide = [[Disruption weapons deal no direct damage, instead building disruptive interference within the target's systems. As disruption accumulates, the target's movement degrades progressively — and so does its ability to perceive the battlefield. At full disruption, the target is locked out entirely: immobilized, nearly blind, and unable to fire for several seconds. Disruption also arcs to nearby enemies on impact, making these weapons particularly effective against clustered formations. Continued fire on a locked-out target is not wasted — the arc still spreads to those around it.]],
		},
		damage                   = {
			default              = 70,
		},
	},

	particlebeamcannon_up2                 = {
		areaofeffect           = 50,
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		cegTag                 = "railgun",
		rgbColor               = "1 0 0",
		rgbColor2              = "1 1 1",
		explosionGenerator     = "custom:genericshellexplosion-medium-sparks-burn",
		edgeEffectiveness	   = 1,
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.25,
		impulseFactor          = 0,
		--interceptedByShieldType  = 4,
		name                   = "E.M.G. Disruption Cannon",
		range                  = 650,
		reloadtime             = 1,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "disruption-laser",
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.6,
		thickness              = 6,
		tolerance              = 10000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 1500,
		customparams             = {
			expl_light_color	= red, -- As a string, RGB
			expl_light_radius	= mediumExplosion, -- In Elmos
			expl_light_life		= mediumExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit          = "true",
			disruptionweapon    = 1,
			weaponguide = [[Disruption weapons deal no direct damage, instead building disruptive interference within the target's systems. As disruption accumulates, the target's movement degrades progressively — and so does its ability to perceive the battlefield. At full disruption, the target is locked out entirely: immobilized, nearly blind, and unable to fire for several seconds. Disruption also arcs to nearby enemies on impact, making these weapons particularly effective against clustered formations. Continued fire on a locked-out target is not wasted — the arc still spreads to those around it.]],
		},
		damage                   = {
			default              = 2000,
		},
	},

	particlebeamcannon_up3                 = {
		areaofeffect           = 50,
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		cegTag                 = "railgun",
		rgbColor               = "1 0 0",
		rgbColor2              = "1 1 1",
		explosionGenerator     = "custom:genericshellexplosion-medium-sparks-burn",
		edgeEffectiveness	   = 1,
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.25,
		impulseFactor          = 0,
		--interceptedByShieldType  = 4,
		name                   = "E.M.G. Disruption Cannon",
		range                  = 700,
		reloadtime             = 1,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "disruption-laser",
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.6,
		thickness              = 6,
		tolerance              = 10000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 1500,
		customparams             = {
			expl_light_color	= red, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit          = "true",
			disruptionweapon    = 1,
			weaponguide = [[Disruption weapons deal no direct damage, instead building disruptive interference within the target's systems. As disruption accumulates, the target's movement degrades progressively — and so does its ability to perceive the battlefield. At full disruption, the target is locked out entirely: immobilized, nearly blind, and unable to fire for several seconds. Disruption also arcs to nearby enemies on impact, making these weapons particularly effective against clustered formations. Continued fire on a locked-out target is not wasted — the arc still spreads to those around it.]],
		},
		damage                   = {
			default              = 20000,
		},
	},

	particlebeamcannon_up4                 = {
		areaofeffect           = 50,
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		cegTag                 = "railgun",
		rgbColor               = "1 0 0",
		rgbColor2              = "1 1 1",
		explosionGenerator     = "custom:genericshellexplosion-medium-sparks-burn",
		edgeEffectiveness	   = 1,
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.25,
		impulseFactor          = 0,
		--interceptedByShieldType  = 4,
		name                   = "E.M.G. Disruption Cannon",
		range                  = 750,
		reloadtime             = 1,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "disruption-laser",
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.6,
		thickness              = 6,
		tolerance              = 10000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 1500,
		customparams             = {
			expl_light_color	= red, -- As a string, RGB
			expl_light_radius	= hugeExplosion, -- In Elmos
			expl_light_life		= hugeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
			single_hit          = "true",
			disruptionweapon    = 1,
			weaponguide = [[Disruption weapons deal no direct damage, instead building disruptive interference within the target's systems. As disruption accumulates, the target's movement degrades progressively — and so does its ability to perceive the battlefield. At full disruption, the target is locked out entirely: immobilized, nearly blind, and unable to fire for several seconds. Disruption also arcs to nearby enemies on impact, making these weapons particularly effective against clustered formations. Continued fire on a locked-out target is not wasted — the arc still spreads to those around it.]],
		},
		damage                   = {
			default              = 50000,
		},
	},
}
