unitDef                     = {

	activatewhenbuilt             = false,
	buildAngle                    = 1024,
	buildCostEnergy               = 0,
	buildCostMetal                = buildCostMetal,
	builder                       = false,
	buildTime                     = 5,
	buildpic					 = "lozgeostub.png",
	canAttack			          = false,
	canBeAssisted                 = false,
	canGuard                      = false,
	canMove                       = false,
	canPatrol                     = false,
	canReclaim		              = false,
	canstop                       = false,
	category                      = "BUILDING",
	description                   = [[Can Upgrade into Various Structures]],
	energyStorage                 = 0,
	energyUse                     = 0,
	energyMake                    = 0,
	explodeAs                     = explodeAs,
	footprintX                    = 5,
	footprintZ                    = 5,
	floater			              = false,
	iconType                      = "factory",
	idleAutoHeal                  = .5,
	idleTime                      = 2200,
	maxDamage                     = 100,
	maxSlope                      = 90,
	maxWaterDepth                 = 0,
	metalStorage                  = 0,
	metalMake                     = 0,
	moveState					  = 0,
	name                          = humanName,
	objectName                    = objectName,
	script						  = script,
	radarDistance                 = 0,
	repairable		              = false,
	selfDestructAs                = explodeAs,
	showNanoSpray                 = true,
	side                          = "CORE",
	sightDistance                 = 0,
	smoothAnim                    = true,
	TEDClass                      = "PLANT",
	unitname                      = unitName,
	--  unitRestricted	          = 1,
	workerTime                    = 0,
	yardMap                       = "ooooo ooooo g ooooo ooooo ooooo",
	--  usePieceCollisionVolumes  = true,
	--  modelCenterOffset	      = {108, 10, 0},
	sfxtypes                      = { 
		pieceExplosionGenerators  = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators       = {
		},
	},

	sounds                        = {
		underattack               = "units_under_attack",
		select                    = {
			"other/gdfactoryselect",
		},
	},
	weapons                       = {
	},
	customParams                  = {
		unitguide = [[The Geothermal Stub is a placeholder structure built on geothermal vent sites, reserving the location for future development. On its own it does nothing, but it marks the vent as claimed and prevents the enemy from building there. Once placed, engineers can upgrade it into a Geothermal Power Plant, a Geothermal E->M Converter, or other vent-specific structures depending on what the economy needs most.]],
		unittype				  = "building",
		unitrole 				  = "Construction Stub",
		buildmenucategory		  = "Utility",
		RequireTech              = tech,
		death_sounds              = "generic",
		normaltex                = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                 = "unittextures/lego2skin_explorerbucket.dds",
		factionname	              = "Federation of Kala",
		
	},
	useGroundDecal                = true,
}
