unitDef                         = {
	activatewhenbuilt                 = true,
	buildCostEnergy                   = buildCostEnergy,
	buildCostMetal                    = 0.1,
	builder                           = true,
	buildTime                         = 2.5,
	buildpic					 	  = "eairplant.png",
	canBeAssisted                     = false,
	canGuard                          = true,
	canMove                           = true,
	canPatrol                         = true,
	canReclaim		                  = false,
	canstop                           = true,
	category                          = "BUILDING",
	description                       = [[Builds Air Units]],
	energyStorage                     = 0,
	energyUse                         = 0,
	energyMake                        = 0,
	explodeAs                         = explodeAs,
	floater			                  = true,
	footprintX                        = 9,
	footprintZ                        = 9,
	iconType                          = "structurefactoryt0",
	idleAutoHeal                      = .5,
	idleTime                          = 2200,
	levelground		                  = false,
	maxDamage                         = 1,
	maxSlope                          = 90,
	maxWaterDepth                     = 999999,
	metalStorage                      = 0,
	metalMake                         = 0,
	mobilestandorders                 = "1",
	name                              = humanName,
	objectName                        = objectName,
	script			                  = script,
	radarDistance                     = 0,
	repairable		                  = false,
	selfDestructAs                    = explodeAs,
	showNanoSpray                     = true,
	sightDistance                     = 500,
	smoothAnim                        = true,
	TEDClass                          = "PLANT",
	unitname                          = unitName,
	--  unitRestricted	              = 1,
	unitnumber                        = "83",
	workerTime                        = workertime,
	yardMap                           = "oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo oooooooooooooooooo",
	--  usePieceCollisionVolumes      = true,

	sfxtypes                          = { 
		pieceExplosionGenerators      = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators           = {
			"custom:nano-animated",
			"custom:nano-animated",
			"custom:blacksmoke",
			"custom:fusionreactionbasic",
			"custom:airfactoryhtrail",
		},
	},
	zbuffer                           = "1",
	
	buildoptions                      = airPlantBuildList,
	
	sounds                         = {
		underattack                = "units_under_attack",
		select                     = {
			"other/gdfactoryselect",
		},
	},
	customParams                      = {
		unitguide = [[The Air Plant is the factory responsible for producing all air units for its faction. It activates immediately on completion and can begin building aircraft as soon as it finishes. A second Air Plant can be built to run parallel production queues when air power is the primary strategic focus. Keep it away from the front line — a destroyed factory cannot be replaced quickly.]],
		unittype				      = "building",
		unitrole 				      = "Factory",
		buildmenucategory		  	  = "Production",
		RequireTech                   = tech,
		death_sounds                  = "generic",
		normaltex                     = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                     = "unittextures/lego2skin_explorerbucket.dds",
		factionname	                  = factionname,
		--	ProvideTech               = "1 Powergrid",
		--    ProvideTechRange        = "1500",
		--	groundtexselectimg        = ":nc:bitmaps/power/powergrid.png",
		--	groundtexselectxsize      = 1500, -- optional
		--    groundtexselectzsize    = 1500, -- optional
	},
	--  useGroundDecal                = true,
	--  BuildingGroundDecalType       = "factorygroundplate.dds",
	--  BuildingGroundDecalSizeX      = 20,
	--  BuildingGroundDecalSizeY      = 20,
	--  BuildingGroundDecalDecaySpeed = 0.9,
}
