unitDef                     = {

	activateWhenBuilt             = true,
	buildAngle                    = 2048,
	buildCostEnergy               = 0,
	buildCostMetal                = buildCostMetal,
	buildingMask				  = 4,
	builder                       = false,
	buildTime                     = 5,
	buildPic					  = "emetalextractor.png",
	canAttack			          = false,
	category                      = "BUILDING",
	description                   = description, --This value is set in alldefspost
	energyStorage                 = 100,
	energyUse                     = 0, -- This value is controlled by game_metal_maker_output_scaler.lua
	explodeAs                     = explodeAsSelfSAs,
	footprintX                    = 5,
	footprintZ                    = 5,
	iconType                      = iconType,
	idleAutoHeal                  = .5,
	idleTime                      = 2200,
	levelground                   = true,
	maxDamage                     = buildCostMetal * 12.5,
	maxSlope                      = 90,
	maxWaterDepth                 = 5000,
	metalStorage                  = 100,
	makesmetal                    = 0, -- This value is controlled by game_metal_maker_output_scaler.lua
	name                          = humanName,
	objectName                    = objectName,
	script						  = script,
	onoffable                     = true,
	radarDistance                 = 0,
	repairable		              = false,
	selfDestructAs                = explodeAsSelfSAs,
	selfDestructCountdown         = 15,
	side                          = "CORE",
	sightDistance                 = 200,
	smoothAnim                    = true,
	unitName                      = unitName,
	workerTime                    = 0,
	yardMap                       = "yoooy yoooy yoooy yoooy yoooy",
	sfxtypes                      = { 
		pieceExplosionGenerators  = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators       = {
			"custom:blacksmoke",
			primaryCEG,
			skyhateceg,
		},
	},
	sounds                        = {
		underattack               = "units_under_attack",
		select                    = {
			"gdmex",
		},
		activate                  = "mexactivate",
		deactivate                = "mexdeactivate",
	},
	weapons                       = {
	},
	customParams                  = {
		unitguide = [[The E->M Converter is the primary metal income structure for both factions, converting energy into metal at a rate scaled by the map's metalSpot_value and the converter's tech tier. Output and energy consumption are set dynamically at runtime by the metal maker scaling system — the higher the map's spot value and the higher the tier, the more metal it produces and the more energy it draws. Higher tiers multiply the base output substantially: Tier 1 doubles it, Tier 2 triples it, Tier 3 produces more than five times the base rate, and Tier 4 more than ten. Place converters on high-value spots and upgrade them as your tech and energy economy allows.]],
		RequireTech				  = tech,
		unittype				  = "building",
		unitrole				  = "Economy",
		buildmenucategory		  = "Economy",
		metal_maker               = true,
		metal_extractor           = true, --Keeping this flag for compatibility
		buildtimemultiplier       = buildtimemultiplier,
		iseco                     = 1,
		needed_cover              = 3,
		death_sounds              = "generic",
		armortype                 = armortype,
		noenergycost			  = noenergycost,
		normaltex                = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                 = "unittextures/lego2skin_explorerbucket.dds",
		factionname	              = faction,
		
	},
	useGroundDecal                = true,
	BuildingGroundDecalType       = "factorygroundplate.dds",
	BuildingGroundDecalSizeX      = 9,
	BuildingGroundDecalSizeY      = 9,
	BuildingGroundDecalDecaySpeed = 0.9,
}
