-- genericshellexplosion-small-green
-- genericshellexplosion-medium-green
-- genericshellexplosion-large-green

return {
  ["genericshellexplosion-small-green"] = {
    flame = {
      air        = true,
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      ground     = true,
      water      = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 1 0 0.05   0.2 0.9 0.2 0.01]],
        directional         = false,
        emitrot             = 70,
        emitrotspread       = 40,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0.25,0]],
        numparticles        = [[1]],
        particlelife        = 5,
        particlelifespread  = 9,
        particlesize        = 18.4,
        particlesizespread  = 18.8,
        particlespeed       = 0.3,
        particlespeedspread = 0.6,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,10]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-anim4]],
        drawOrder           = 0,
        castShadow          = true,
      },
    },
	
	-- put this next to groundflash
	-- explosionwave = {
    --   air                = true,
    --   class              = [[CSimpleParticleSystem]],
    --   count              = 1,
    --   ground             = true,
    --   water              = true, 
	--   underwater         = true,
    --   properties = {
    --     airdrag            = 0.87,
    --     alwaysvisible      = true,
    --     colormap           = [[0 1 0 0.05	0 0 0 0.0]], -- same as groundflash colors
    --     directional        = false,
    --     emitrot            = 90,
    --     emitrotspread      = 5,
    --     emitvector         = [[0, 0, 0]],
    --     gravity            = [[0, 0, 0]],
    --     numparticles       = 1,
    --     particlelife       = [[20]], -- same as groundflash ttl
    --     particlelifespread = 0,
    --     particlesize       = 2, -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
    --     particlesizespread = 1,
    --     particlespeed      = [[8]],
    --     particlespeedspread = 6,
    --     pos                = [[0, 1, 0]],
    --     sizegrowth         = 3, -- same as groundflash circlegrowth
    --     sizemod            = 1.0,
    --     texture            = [[explosionwave]],
    --   },
    -- },

    kickedupdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.25 0.20 0.10 0.35	0 0 0 0.0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = 30,
        particlelife       = 2,
        particlelifespread = 30,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 6,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke]],
      },
    },
    kickedupwater = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.7 0.7 0.9 0.35	0 0 0 0.0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = 30,
        particlelife       = 2,
        particlelifespread = 30,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 6,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[wake]],
      },
    },
    greenexplosionspikes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0 1 0 0.05   0.2 0.9 0.2 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 8,
        particlelife       = 8,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 3,
        particlespeedspread = 2,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[flashside2]],
        useairlos          = false,
      },
    },
    -- outerflash = {
    --   air                = true,
    --   class              = [[heatcloud]],
    --   count              = 2,
    --   ground             = true,
    --   water              = true, 
	--   underwater         = true,
    --   properties = {
    --     alwaysvisible      = true,
    --     heat               = 10,
    --     heatfalloff        = 1.1,
    --     maxheat            = 20,
    --     pos                = [[r-2 r2, 5, r-2 r2]],
    --     size               = 1,
    --     sizegrowth         = 10,
    --     speed              = [[0, 1 0, 0]],
    --     texture            = [[greennovaexplo]],
    --   },
    -- },
  },

  ["genericshellexplosion-medium-green"] = {
    flame = {
      air        = true,
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      ground     = true,
      water      = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 1 0 0.05   0.2 0.9 0.2 0.01]],
        directional         = false,
        emitrot             = 70,
        emitrotspread       = 40,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0.25,0]],
        numparticles        = [[1]],
        particlelife        = 5,
        particlelifespread  = 9,
        particlesize        = 18.4,
        particlesizespread  = 18.8,
        particlespeed       = 0.3,
        particlespeedspread = 0.6,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,10]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-anim4]],
        drawOrder           = 0,
        castShadow          = true,
      },
    },
	
	-- put this next to groundflash
	-- explosionwave = {
    --   air                = true,
    --   class              = [[CSimpleParticleSystem]],
    --   count              = 1,
    --   ground             = true,
    --   water              = true, 
	--   underwater         = true,
    --   properties = {
    --     airdrag            = 0.87,
    --     alwaysvisible      = true,
    --     colormap           = [[0 1 0 0.05	0 0 0 0.0]], -- same as groundflash colors
    --     directional        = false,
    --     emitrot            = 90,
    --     emitrotspread      = 5,
    --     emitvector         = [[0, 0, 0]],
    --     gravity            = [[0, 0, 0]],
    --     numparticles       = 1,
    --     particlelife       = [[20]], -- same as groundflash ttl
    --     particlelifespread = 0,
    --     particlesize       = 4, -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
    --     particlesizespread = 1,
    --     particlespeed      = [[8]],
    --     particlespeedspread = 6,
    --     pos                = [[0, 1, 0]],
    --     sizegrowth         = 6, -- same as groundflash circlegrowth
    --     sizemod            = 1.0,
    --     texture            = [[explosionwave]],
    --   },
    -- },

    kickedupdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.25 0.20 0.10 0.35	0 0 0 0.0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = 60,
        particlelife       = 2,
        particlelifespread = 30,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 5,
        particlespeedspread = 6,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke]],
      },
    },
    kickedupwater = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.7 0.7 0.9 0.35	0 0 0 0.0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = 60,
        particlelife       = 2,
        particlelifespread = 30,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 5,
        particlespeedspread = 6,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[wake]],
      },
    },
    greenexplosionspikes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0 1 0 0.05   0.2 0.9 0.2 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 8,
        particlelife       = 8,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 8,
        particlespeedspread = 2,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[flashside2]],
        useairlos          = false,
      },
    },
    -- outerflash = {
    --   air                = true,
    --   class              = [[heatcloud]],
    --   count              = 2,
    --   ground             = true,
    --   water              = true, 
	--   underwater         = true,
    --   properties = {
    --     alwaysvisible      = true,
    --     heat               = 10,
    --     heatfalloff        = 1.1,
    --     maxheat            = 20,
    --     pos                = [[r-2 r2, 5, r-2 r2]],
    --     size               = 1,
    --     sizegrowth         = 15,
    --     speed              = [[0, 1 0, 0]],
    --     texture            = [[greennovaexplo]],
    --   },
    -- },
  },

  ["genericshellexplosion-large-green"] = {
    flame = {
      air        = true,
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      ground     = true,
      water      = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 1 0 0.05   0.2 0.9 0.2 0.01]],
        directional         = false,
        emitrot             = 70,
        emitrotspread       = 40,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0.25,0]],
        numparticles        = [[1]],
        particlelife        = 5,
        particlelifespread  = 9,
        particlesize        = 18.4,
        particlesizespread  = 18.8,
        particlespeed       = 0.3,
        particlespeedspread = 0.6,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,10]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-anim4]],
        drawOrder           = 0,
        castShadow          = true,
      },
    },
	
	-- put this next to groundflash
	-- explosionwave = {
    --   air                = true,
    --   class              = [[CSimpleParticleSystem]],
    --   count              = 1,
    --   ground             = true,
    --   water              = true, 
	--   underwater         = true,
    --   properties = {
    --     airdrag            = 0.87,
    --     alwaysvisible      = true,
    --     colormap           = [[0 1 0 0.05	0 0 0 0.0]], -- same as groundflash colors
    --     directional        = false,
    --     emitrot            = 90,
    --     emitrotspread      = 5,
    --     emitvector         = [[0, 0, 0]],
    --     gravity            = [[0, 0, 0]],
    --     numparticles       = 1,
    --     particlelife       = [[20]], -- same as groundflash ttl
    --     particlelifespread = 0,
    --     particlesize       = 6, -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
    --     particlesizespread = 1,
    --     particlespeed      = [[8]],
    --     particlespeedspread = 6,
    --     pos                = [[0, 1, 0]],
    --     sizegrowth         = 12, -- same as groundflash circlegrowth
    --     sizemod            = 1.0,
    --     texture            = [[explosionwave]],
    --   },
    -- },

    kickedupdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.25 0.20 0.10 0.35	0 0 0 0.0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = 120,
        particlelife       = 2,
        particlelifespread = 30,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 6,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke]],
      },
    },
    kickedupwater = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.7 0.7 0.9 0.35	0 0 0 0.0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = 120,
        particlelife       = 2,
        particlelifespread = 30,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 6,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[wake]],
      },
    },
    greenexplosionspikes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0 1 0 0.05   0.2 0.9 0.2 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 8,
        particlelife       = 8,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 12,
        particlespeedspread = 2,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[flashside2]],
        useairlos          = false,
      },
    },
    -- outerflash = {
    --   air                = true,
    --   class              = [[heatcloud]],
    --   count              = 2,
    --   ground             = true,
    --   water              = true, 
	--   underwater         = true,
    --   properties = {
    --     alwaysvisible      = true,
    --     heat               = 10,
    --     heatfalloff        = 1.1,
    --     maxheat            = 20,
    --     pos                = [[r-2 r2, 5, r-2 r2]],
    --     size               = 1,
    --     sizegrowth         = 30,
    --     speed              = [[0, 1 0, 0]],
    --     texture            = [[greennovaexplo]],
    --   },
    -- },
  },

}

