-- genericshellexplosion-small
-- genericshellexplosion
-- genericshellexplosion-medium
-- genericshellexplosion-large

return {
  ["genericshellexplosion-small"] = {
    fireball = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0   1 0.7 0 0.1   1 0.3 0 0.1   0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 5,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
    sparks = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0   1 1 1 1   1 0.7 0.2 0.5    0.9 0.2 0.2 0.1    0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 5,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-sparks2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
    smoke = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0    0 0 0 0.2     0 0 0 0.2    0 0 0 0.2     0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 5,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
  },

  ["genericshellexplosion-medium"] = {
    fireball = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0   1 0.7 0 0.1   1 0.3 0 0.1   0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 20,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
    sparks = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0   1 1 1 1   1 0.7 0.2 0.5    0.9 0.2 0.2 0.1    0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 20,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-sparks2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
    smoke = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0    0 0 0 0.2     0 0 0 0.2    0 0 0 0.2     0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 20,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
  },

  ["genericshellexplosion-large"] = {
    fireball = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0   1 0.7 0 0.1   1 0.3 0 0.1   0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 30,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
    sparks = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0   1 1 1 1   1 0.7 0.2 0.5    0.9 0.2 0.2 0.1    0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 30,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-sparks2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
    smoke = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0 0 0 0    0 0 0 0.2     0 0 0 0.2    0 0 0 0.2     0 0 0 0]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 0,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 30,
        particlesizespread  = 0,
        particlespeed       = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[4,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,0,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact2]],
        drawOrder           = 0,
        -- castshadow          = true,
      },
    },
  },

}

