-- genericshellexplosion-small
-- genericshellexplosion
-- genericshellexplosion-medium
-- genericshellexplosion-large

return {
  ["genericshellexplosion-small"] = {
    fireball = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0.9 0.7 0.2 0.5 0.9 0.5 0.2 0.001]],
        directional         = false,
        emitrot             = 70,
        emitrotspread       = 40,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0.1,0]],
        numparticles        = 1,
        particlelife        = 10,
        particlelifespread  = 9,
        particlesize        = 20,
        particlesizespread  = 0,
        particlespeed       = 0.3,
        particlespeedspread = 0.6,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[8,4,15]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,4,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact]],
        drawOrder           = 0,
        castShadow          = true,
      },
    },
    sparks = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap            = [[1 1 1 1   1 0.7 0.2 0.5    0.9 0.2 0.2 0.001]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 1,
        particlelife       = 10,
        particlelifespread = 0,
        particlesize       = 40,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        pos                = [[0, 4, 0]],
        animParams          = [[8,4,15]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture             = [[generated-sparks]],
        useairlos          = false,
      },
    },
    smoke = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0 0 0 1     0 0 0 0.75    0 0 0 0.5     0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 20,
        particlelifespread = 0,
        particlesize       = 20,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        pos                = [[0, 4, 0]],
        animParams          = [[8,4,20]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture             = [[generated-smoke]],
      },
    },
  },

  ["genericshellexplosion-medium"] = {
    fireball = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0.9 0.7 0.2 0.5 0.9 0.5 0.2 0.001]],
        directional         = false,
        emitrot             = 70,
        emitrotspread       = 40,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0.1,0]],
        numparticles        = 1,
        particlelife        = 15,
        particlelifespread  = 9,
        particlesize        = 30,
        particlesizespread  = 0,
        particlespeed       = 0.3,
        particlespeedspread = 0.6,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[8,4,22.5]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,4,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact]],
        drawOrder           = 0,
        castShadow          = true,
      },
    },
    sparks = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap            = [[1 1 1 1   1 0.7 0.2 0.5    0.9 0.2 0.2 0.001]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 1,
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = 60,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        pos                = [[0, 4, 0]],
        animParams          = [[8,4,22.5]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture             = [[generated-sparks]],
        useairlos          = false,
      },
    },
    smoke = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0 0 0 1     0 0 0 0.75    0 0 0 0.5     0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 30,
        particlelifespread = 0,
        particlesize       = 30,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        pos                = [[0, 4, 0]],
        animParams          = [[8,4,30]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture             = [[generated-smoke]],
      },
    },
  },

  ["genericshellexplosion-large"] = {
    fireball = {
      class      = [[CSimpleParticleSystem]],
      count      = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[0.9 0.7 0.2 0.5 0.9 0.5 0.2 0.001]],
        directional         = false,
        emitrot             = 70,
        emitrotspread       = 40,
        emitvector          = [[0,0,0]],
        gravity             = [[0,0.1,0]],
        numparticles        = 1,
        particlelife        = 20,
        particlelifespread  = 9,
        particlesize        = 40,
        particlesizespread  = 0,
        particlespeed       = 0.3,
        particlespeedspread = 0.6,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        animParams          = [[8,4,30]], --[xTiles, yTiles, animLength in game frames]
        pos                 = [[0,4,0]],
        sizegrowth          = 0.5,
        sizemod             = 1,
        texture             = [[generated-impact]],
        drawOrder           = 0,
        castShadow          = true,
      },
    },
    sparks = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap            = [[1 1 1 1   1 0.7 0.2 0.5    0.9 0.2 0.2 0.001]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 1,
        particlelife       = 20,
        particlelifespread = 0,
        particlesize       = 80,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        pos                = [[0, 4, 0]],
        animParams          = [[8,4,30]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture             = [[generated-sparks]],
        useairlos          = false,
      },
    },
    smoke = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      air        = true,
      ground     = true,
      water      = true,
      underwater = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0 0 0 1     0 0 0 0.75    0 0 0 0.5     0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 40,
        particlelifespread = 0,
        particlesize       = 40,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        rotParams           = [[-24 r48, -60 r120, -180 r360]],
        pos                = [[0, 4, 0]],
        animParams          = [[8,4,40]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture             = [[generated-smoke]],
      },
    },
  },

}

