unitDef                     = {
	buildAngle                    = 8192,
	buildCostEnergy               = 0,
	buildCostMetal                = 7000,
	builder                       = false,
	buildTime                     = 5,
	buildpic					  = "eheavyturret2.png",
	canAttack                     = true,
	canstop                       = "1",
	category                      = "BUILDING",
	description                   = [[Heavy Plasma Battery (Anti-Armor)]],
	energyStorage                 = 0,
	energyUse                     = 0,
	explodeAs                     = "hugeBuildingExplosionGenericRed",
	footprintX                    = 12,
	footprintZ                    = 12,
	floater			              = false,
	idleAutoHeal                  = .5,
	idleTime                      = 2200,
	iconType                      = "defenseturret",
	maxDamage                     = 1200,
	maxSlope                      = 60,
	maxWaterDepth                 = 0,
	metalStorage                  = 0,
	name                          = humanName,
	objectName                    = objectName,
	script						  = script,
	radarDistance                 = 0,
	repairable		              = false,
	selfDestructAs                = "hugeBuildingExplosionGenericRed",
	side                          = "CORE",
	sightDistance                 = 1000,
	smoothAnim                    = true,
	unitname                      = unitName,
	workerTime                    = 0,
	yardMap                       = "oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo g oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo",

	sfxtypes                      = { 
		pieceExplosionGenerators  = { 
			"deathceg3",
			"deathceg4",
		}, 

		explosiongenerators       = {
			"custom:gdhcannon",
			"custom:needspower",
			"custom:burnblack",
		},
	},
	sounds                        = {
		underattack               = "other/unitsunderattack1",
		select                    = {
			"other/turretselect",
		},
	},
	weapons                       = {
		[1]                       = {
			def                   = "BeamLaser",
			badTargetCategory     = "BUILDING GROUND SHIP",
			onlyTargetCategory    = "MASSIVE GROUND BUILDING SHIP",
		},
	},
	customParams                  = {
		unittype				  = "building",
		unitrole				  = "Single-Target Turret",
		unitrole_sound            = "turret",
		needed_cover              = 5,
		--supply_cost               = supply,
		RequireTech				  = tech,
		death_sounds              = "generic",
		normaltex                 = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                 = "unittextures/lego2skin_explorerbucket.dds",
		factionname	              = "Loz Alliance",
		corpse                   = "energycore",
	},
	useGroundDecal                = true,
	BuildingGroundDecalType       = "factorygroundplate.dds",
	BuildingGroundDecalSizeX      = 8,
	BuildingGroundDecalSizeY      = 8,
	BuildingGroundDecalDecaySpeed = 0.9,
}

weaponDefs                  = {
	BeamLaser           = {
		avoidFeature              = false,
		avoidFriendly             = false,
		collideFeature            = false,
		collideFriendly           = false,
		coreThickness             = 0.5,
		-- cegtag					  = "burnblack",
		-- beamDecay                 = 0.9,
		beamtime				  = 0.5,
		beamttl                   = 10,
		largebeamlaser			  = true,
		sweepfire				  = false,
		duration                  = 0.8,
		energypershot             = 0,
		edgeeffectiveness		  = 0,
		explosionGenerator        = "custom:genericshellexplosion-large",
		fallOffRate               = 0.1,
		fireStarter               = 100,
		impulseFactor             = 0,
		interceptedByShieldType   = 4,
		minintensity              = 1,
		name                      = "High Intensity BeamLaser",
		range                     = 1200,
		reloadtime                = 2,
		WeaponType                = "BeamLaser",
		rgbColor                  = blue,
		rgbColor2                 = "0.25 0.25 0.25",
		soundTrigger              = true,
		soundstart                = "lozannihilator-maingun",
		-- soundHit                  = "explode5",
		-- sprayangle				  = 500,
		texture1                  = "lightning",
		texture2                  = "flash1",
		texture3                  = "flash1",
		texture4                  = "flash1",
		thickness                 = 12,
		tolerance                 = 500,
		turret                    = true,
		weaponVelocity            = 750,
		waterweapon				 = false,
		customparams              = {
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                    = {
			default               = 1675,
		},
	},
}