unitDef                     = {
	buildAngle                    = 8192,
	buildCostEnergy               = 0,
	buildCostMetal                = 1000,
	builder                       = false,
	buildTime                     = 5,
	buildpic					  = "eheavyturret2.png",
	canAttack                     = true,
	canstop                       = "1",
	category                      = "BUILDING",
	description                   = [[Short Range Burst Anti-Air]],
	energyStorage                 = 0,
	energyUse                     = 0,
	explodeAs                     = "largeBuildingExplosionGenericRed",
	footprintX                    = 4,
	footprintZ                    = 4,
	floater			              = false,
	idleAutoHeal                  = .5,
	idleTime                      = 2200,
	iconType                      = "structureaat2",
	maxDamage                     = 1200,
	maxSlope                      = 60,
	maxWaterDepth                 = 0,
	metalStorage                  = 0,
	name                          = humanName,
	objectName                    = objectName,
	script						  = script,
	radarDistance                 = 0,
	repairable		              = false,
	selfDestructAs                = "largeBuildingExplosionGenericRed",
	side                          = "CORE",
	sightDistance                 = 500,
	smoothAnim                    = true,
	unitname                      = unitName,
	workerTime                    = 0,
	yardMap                       = "oooo oooo oooo oooo oooo oooo oooo oooo oooo",

	sfxtypes                      = { 
		pieceExplosionGenerators  = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators       = {
			"custom:gdhcannon",
			"custom:needspower",
			"custom:burnblack",
		},
	},
	sounds                        = {
		underattack               = "units_under_attack",
		select                    = {
			"other/turretselect",
		},
	},
	weapons                       = {
		[1]                       = {
			def                   = "flakcannon",
			onlyTargetCategory    = "AIR",
		},
	},
	customParams                  = {
		unitguide = [[The Rattlesnake is the Loz Alliance's Tier 2 anti-air turret, firing high-explosive flak rounds that detonate in the airspace above and scatter lethal fragments across a wide area. Its large blast radius and high damage per shot make it exceptionally effective against both individual aircraft and formations attempting to pass through its coverage zone. Aircraft that ignore the Rattlesnake rarely get a second chance to do so.]],
		buildtimemultiplier       = buildtimemultiplier,
		unittype				  = "building",
		unitrole				  = "Medium Range Anti-Air",
		unitrole_sound            = "turret",
		buildmenucategory         = "Combat",
		needed_cover              = 5,
		--supply_cost               = supply,
		RequireTech				  = tech,
		death_sounds              = "generic",
		normaltex                 = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                 = "unittextures/lego2skin_explorerbucket.dds",
		factionname	              = "Loz Alliance",
		
	},
	useGroundDecal                = true,
	BuildingGroundDecalType       = "factorygroundplate.dds",
	BuildingGroundDecalSizeX      = 8,
	BuildingGroundDecalSizeY      = 8,
	BuildingGroundDecalDecaySpeed = 0.9,
}

weaponDefs                  = {
	flakcannon   	             = {
		predictboost	         = 0.3,
		AreaOfEffect             = 200,
		avoidFeature             = false,
		avoidFriendly            = false,
		collideFeature           = false,
		collideFriendly          = false,
		canAttackGround 		 = false,
		coreThickness            = 0.5,
		burnblow		         = true,
		--cegTag                   = "railgun",
		duration                 = 0.05,
		energypershot            = 0,
		explosionGenerator       = "custom:genericshellexplosion-large",
		edgeEffectiveness		 = 1,
		fallOffRate              = 1,
		fireStarter              = 50,
		impulseFactor            = 0,
		minintensity             = "1",
		model                   = "projectile/projectileorange.s3o",
		name                     = "High Explosive Flak Cannon",
		range                    = 1650,
		reloadtime               = 3,
		WeaponType               = "Cannon",
		rgbColor                 = "1 0.5 0",
		rgbColor2                = "1 1 1",
		soundTrigger             = false,
		soundstart               = "Assault Rifle Shot_05",
		soundhit				 = "Explosion Fireworks_01",
		-- sprayangle				 = 500,
		size					 = 6,
		--texture1                 = "shot",
		--texture2                 = "empty",
		tolerance                = 7500,
		turret                   = true,
		weaponVelocity           = 5000,
		customparams             = {
			weaponguide = [[A high-explosive flak cannon that fires self-detonating rounds into the airspace, creating a large lethal fragment cloud on detonation. The enormous area of effect and high damage per shot make it one of the most dangerous anti-air emplacements in the game.]],
			expl_light_color	= purple, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= mediumExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                   = {
			default              = 810,
		},
	},
}