unitDef                    = {
	--acceleration                 = 0.5,
	airStrafe                    = false,
	airHoverFactor				 = 0,
	BadTargetCategory            = "VTOL",
	--brakeRate                    = 1,
	buildCostEnergy              = 750000,
	buildCostMetal               = 0,
	builder                      = false,
	buildTime                    = 5,
	buildpic					 = "ekrow.png",
	canAttack                    = true,
	canFly                       = true,
	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = true,
	category                     = "AIR",
	collide                      = true,
	cruiseAlt                    = 400,
	description                  = [[Endbringer Flying Fortress]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = "hugeExplosionGeneric",
	footprintX                   = 10,
	footprintZ                   = 10,
	floater                      = true,
	hoverAttack                  = true,
	iconType                     = "krow",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	loopbackattack               = false,
	maxDamage                    = 24000,
	maxSlope                     = 90,
	maxVelocity                  = 1.5,
	verticalSpeed		         = 15,
	maxWaterDepth                = 0,
	metalStorage                 = 0,
	name                         = humanName,
	noChaseCategory              = "VTOL",
	objectName                   = objectName,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = "hugeExplosionGeneric",
	side                         = "CORE",
	sightDistance                = 1050,
	smoothAnim                   = true,
	stealth                      = false,
	transportbyenemy             = false;
	turnRate                     = 100,
	unitname                     = unitName,
	upright						 = true,
	workerTime                   = 0,
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:gdhcannon",
			"custom:blacksmoke",
		},
	},
	sounds                       = {
		underattack              = "units_under_attack",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = "aircannon",
			onlyTargetCategory   = "GROUND BUILDING SHIP",
			mainDir              = "0 -1 0",
			maxAngleDif          = 170,
		},
	},
	customParams                 = {
		unittype				 = "air",
		unitrole				 = "Combat Transport",
		death_sounds             = "generic",
		nofriendlyfire           = "1",
		normaltex                = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		factionname	             = "Neutral",
	},
}

weaponDefs                 = {
	aircannon   	             = {
		AreaOfEffect             = 200,
		avoidFeature             = false,
		avoidFriendly            = false,
		collideFeature           = false,
		collideFriendly          = false,
		coreThickness            = 0.5,
		beamTime                 = 0.1,
		beamTTL					 = 10,
		beamDecay				 = 1,
		burnblow		         = true,
		largeBeamLaser           = true,
		laserflaresize 	         = 7,
		minIntensity			 = 1,
		--cegTag                   = "railgun",
		heightmod				 = 1,
		duration                 = 0.6,
		edgeeffectiveness		 = 1,
		energypershot            = 0,
		explosionGenerator       = "custom:genericshellexplosion-large-red",
		fireStarter              = 50,
		impulseFactor            = 0,
		fallOffRate				 = 0,
		interceptedByShieldType  = 4,
		minintensity             = 1,
		name                     = "Laser",
		range                    = 800,
		reloadtime               = 2,
		WeaponType               = "BeamLaser",
		waterweapon				 = true,
		rgbColor                 = "0.4 0.2 0.5",
		rgbColor2                = "1 1 1",
		soundTrigger             = true,
		soundstart               = "eturretfire",
		soundHit                 = "artyhit",
		texture1                  = "lightning",
		texture2                  = "laserend",
		thickness                = 25,
		tolerance                = 10000,
		turret                   = true,
		weaponVelocity           = 750,
		customparams             = {

		}, 
		damage                   = {
			default              = 1000,
		},
	},
}
