function widget:GetInfo()
	return {
		name    = "Disruption Electricity",
		desc    = "Draws crawling electricity over disrupted units; intensity scales with disruption stage",
		author  = "",
		date    = "2026-07-04",
		license = "MIT",
		layer   = 100,
		enabled = true,
	}
end

--------------------------------------------------------------------------------
-- Config
--------------------------------------------------------------------------------

-- User-supplied texture. Requirements:
--   * Tileable (seamless) grayscale noise -- perlin clouds, caustics, or a
--     lightning/plasma pattern all work. Brightness is used as a noise field;
--     the arcs are generated by interference thresholding, so it does NOT
--     need to look like lightning itself.
--   * 256x256 or 512x512 is plenty.
local ELECTRIC_TEX = "LuaUI/Images/disruption_electric.png"

-- Minimum stage at which the effect shows (1 = sensors offline)
local MIN_STAGE = 1

-- Arc color per stage (RGB); blended smoothly as disruption rises
local COLOR_LOW  = { 0.25, 0.75, 1.00 } -- stage 1: electric blue
local COLOR_HIGH = { 0.75, 0.55, 1.00 } -- stage 3: violet-white

-- Effect shaping
local INTENSITY_BASE   = 0.30  -- intensity at stage 1 threshold
local INTENSITY_MAX    = 1.00  -- intensity at full disruption
local SPEED_BASE       = 1.0   -- texture scroll speed multiplier at low disruption
local SPEED_FULL       = 2.2   -- scroll speed at full disruption
local INFLATE_ELMOS    = 0.45  -- how far the overlay shell sits off the hull
local JITTER_FULL      = 1.4   -- vertex jitter amplitude (elmos) at stage 3 only
local FLICKER_AMOUNT   = 0.25  -- 0..1, random brightness flicker strength

-- How often (seconds) to rescan visible units for disruption params
local SCAN_PERIOD = 0.15

--------------------------------------------------------------------------------
-- Speedups
--------------------------------------------------------------------------------

local spGetVisibleUnits    = Spring.GetVisibleUnits
local spGetUnitRulesParam  = Spring.GetUnitRulesParam
local spValidUnitID        = Spring.ValidUnitID
local spIsUnitIcon         = Spring.IsUnitIcon
local spGetGameFrame       = Spring.GetGameFrame
local spGetFrameTimeOffset = Spring.GetFrameTimeOffset
local spEcho               = Spring.Echo

local glUseShader   = gl.UseShader
local glTexture     = gl.Texture
local glUnit        = gl.Unit
local glDepthTest   = gl.DepthTest
local glDepthMask   = gl.DepthMask
local glBlending    = gl.Blending
local glCulling     = gl.Culling
local glUniform     = gl.Uniform
local glPolygonOffset = gl.PolygonOffset

local GL_SRC_ALPHA = GL.SRC_ALPHA
local GL_ONE       = GL.ONE
local GL_ONE_MINUS_SRC_ALPHA = GL.ONE_MINUS_SRC_ALPHA
local GL_LEQUAL    = GL.LEQUAL
local GL_BACK      = GL.BACK

local GAME_SPEED = 30

--------------------------------------------------------------------------------
-- State
--------------------------------------------------------------------------------

local shader
local uniformLocs = {} -- time, intensity, speedMult, jitter, seed, arcColor, useTex, inflate

local tracked = {}      -- unitID -> { stage, pct }
local trackedCount = 0
local scanAccum = 0
local hasTexture = false

--------------------------------------------------------------------------------
-- Shaders (compatibility profile: gl.Unit raw draws use fixed-function matrices)
--------------------------------------------------------------------------------

local vsSrc = [[
uniform float time;
uniform float jitter;
uniform float seed;
uniform float inflate;

varying vec2 modelUV;
varying vec3 modelPos;

float hash13(vec3 p) {
	p = fract(p * 0.1031);
	p += dot(p, p.yzx + 33.33);
	return fract((p.x + p.y) * p.z);
}

void main() {
	vec4 pos = gl_Vertex;
	vec3 n = normalize(gl_Normal);

	// Shell the overlay slightly off the hull (also avoids z-fighting)
	pos.xyz += n * inflate;

	// Stage 3: violent vertex jitter, quantized in time so it strobes
	if (jitter > 0.0) {
		float tick = floor(time * 24.0);
		float h = hash13(pos.xyz * 0.37 + vec3(tick + seed));
		pos.xyz += n * (h - 0.5) * 2.0 * jitter;
	}

	modelUV  = gl_MultiTexCoord0.xy;
	modelPos = gl_Vertex.xyz;

	gl_Position = gl_ModelViewProjectionMatrix * pos;
}
]]

local fsSrc = [[
uniform sampler2D electricTex;
uniform float time;
uniform float intensity;
uniform float speedMult;
uniform float seed;
uniform float useTex;
uniform vec3  arcColor;

varying vec2 modelUV;
varying vec3 modelPos;

// --- cheap procedural fallback noise (used when no texture is supplied) ---
float hash12(vec2 p) {
	vec3 p3 = fract(vec3(p.xyx) * 0.1031);
	p3 += dot(p3, p3.yzx + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}

float vnoise(vec2 p) {
	vec2 i = floor(p);
	vec2 f = fract(p);
	f = f * f * (3.0 - 2.0 * f);
	float a = hash12(i);
	float b = hash12(i + vec2(1.0, 0.0));
	float c = hash12(i + vec2(0.0, 1.0));
	float d = hash12(i + vec2(1.0, 1.0));
	return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

float fbm(vec2 p) {
	return vnoise(p) * 0.6 + vnoise(p * 2.7) * 0.4;
}

float field(vec2 uv) {
	if (useTex > 0.5) {
		return texture2D(electricTex, uv).r;
	}
	return fbm(uv * 5.0);
}
// --------------------------------------------------------------------------

void main() {
	float t = time * speedMult + seed * 17.31;

	// Two noise layers scrolling against each other; their interference
	// produces wandering filaments when thresholded.
	vec2 uv1 = modelUV * 3.0 + vec2( t * 0.35, -t * 0.21);
	vec2 uv2 = modelUV * 2.0 + vec2(-t * 0.27,  t * 0.33);

	float n1 = field(uv1);
	float n2 = field(uv2);
	float interference = n1 * n2;

	// Thin bright arcs where the interference crosses a band
	float band = abs(interference - 0.25);
	float arc  = 1.0 - smoothstep(0.0, 0.10, band);

	// Soft ambient crackle glow
	float glow = interference * 0.30;

	// Random flicker
	float flick = 1.0 - FLICKER * hash12(vec2(floor(time * 30.0), seed));

	float a = (arc + glow) * intensity * flick;

	vec3 color = arcColor * (arc * 1.6 + glow) + vec3(arc * 0.35); // arcs whiten
	gl_FragColor = vec4(color, a);
}
]]

--------------------------------------------------------------------------------
-- Widget lifecycle
--------------------------------------------------------------------------------

function widget:Initialize()
	if not gl.CreateShader then
		spEcho("[DisruptionElectricity] gl.CreateShader unavailable; removing widget")
		widgetHandler:RemoveWidget(self)
		return
	end

	hasTexture = VFS.FileExists(ELECTRIC_TEX)
	if not hasTexture then
		spEcho("[DisruptionElectricity] texture not found at " .. ELECTRIC_TEX
			.. " -- using procedural fallback noise")
	end

	local fs = fsSrc:gsub("FLICKER", string.format("%.4f", FLICKER_AMOUNT))

	shader = gl.CreateShader({
		vertex   = vsSrc,
		fragment = fs,
		uniformInt = {
			electricTex = 0,
		},
	})

	if not shader then
		spEcho("[DisruptionElectricity] shader compile failed:")
		spEcho(gl.GetShaderLog())
		widgetHandler:RemoveWidget(self)
		return
	end

	for _, name in ipairs({ "time", "intensity", "speedMult", "jitter",
			"seed", "useTex", "arcColor", "inflate" }) do
		uniformLocs[name] = gl.GetUniformLocation(shader, name)
	end
end

function widget:Shutdown()
	if shader then
		gl.DeleteShader(shader)
		shader = nil
	end
end

--------------------------------------------------------------------------------
-- Tracking
--------------------------------------------------------------------------------

local function RescanUnits()
	tracked = {}
	trackedCount = 0

	local visible = spGetVisibleUnits(-1, nil, false)
	if not visible then return end

	for i = 1, #visible do
		local unitID = visible[i]
		local stage = spGetUnitRulesParam(unitID, "disruption_stage")
		if stage and stage >= MIN_STAGE then
			local pct = (spGetUnitRulesParam(unitID, "disruption") or 0) * 0.01
			tracked[unitID] = { stage = stage, pct = pct }
			trackedCount = trackedCount + 1
		end
	end
end

function widget:Update(dt)
	scanAccum = scanAccum + dt
	if scanAccum >= SCAN_PERIOD then
		scanAccum = 0
		RescanUnits()
	end
end

--------------------------------------------------------------------------------
-- Drawing
--------------------------------------------------------------------------------

local function Lerp(a, b, t)
	return a + (b - a) * t
end

function widget:DrawWorld()
	if trackedCount == 0 or not shader then
		return
	end

	local time = (spGetGameFrame() + spGetFrameTimeOffset()) / GAME_SPEED

	glUseShader(shader)
	glUniform(uniformLocs.time, time)
	glUniform(uniformLocs.useTex, hasTexture and 1 or 0)
	glUniform(uniformLocs.inflate, INFLATE_ELMOS)

	if hasTexture then
		glTexture(0, ELECTRIC_TEX)
	end

	glDepthTest(GL_LEQUAL)
	glDepthMask(false)
	glBlending(GL_SRC_ALPHA, GL_ONE) -- additive
	glCulling(GL_BACK)
	glPolygonOffset(-2, -2)

	for unitID, data in pairs(tracked) do
		if spValidUnitID(unitID) and not spIsUnitIcon(unitID) then
			local pct   = data.pct
			local stage = data.stage
			local full  = (stage >= 3)

			local intensity = Lerp(INTENSITY_BASE, INTENSITY_MAX, pct)
			local speed     = Lerp(SPEED_BASE, SPEED_FULL, pct)
			local jitter    = full and JITTER_FULL or 0
			if full then
				intensity = INTENSITY_MAX
				speed = SPEED_FULL
			end

			local r = Lerp(COLOR_LOW[1], COLOR_HIGH[1], pct)
			local g = Lerp(COLOR_LOW[2], COLOR_HIGH[2], pct)
			local b = Lerp(COLOR_LOW[3], COLOR_HIGH[3], pct)

			glUniform(uniformLocs.intensity, intensity)
			glUniform(uniformLocs.speedMult, speed)
			glUniform(uniformLocs.jitter, jitter)
			glUniform(uniformLocs.seed, (unitID % 97) * 0.618)
			glUniform(uniformLocs.arcColor, r, g, b)

			glUnit(unitID, true, -1)
		end
	end

	glPolygonOffset(false)
	glCulling(false)
	glBlending(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
	glDepthMask(false)
	glDepthTest(true)

	glTexture(0, false)
	glUseShader(0)
end
