unitDef                    = {
	buildCostEnergy              = 0,
	buildCostMetal               = 2300,
	builder                      = false,
	buildTime                    = 5,
	buildpic					 = "lozmammoth.png",
	canAttack                    = true,
	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = "1",
	category                     = "GROUND MASSIVE",
	description                  = [[Main Battle Tank]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = explodeAs,
	footprintX                   = 7,
	footprintZ                   = 7,
	iconType                     = "assault",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	leaveTracks                  = false,
	maxDamage                    = 375,
	maxSlope                     = 26,
	maxVelocity                  = 2.2,
	maxReverseVelocity           = 1,
	maxWaterDepth                = 10,
	metalStorage                 = 0,
	movementClass                = "WHEELEDTANK7",
	name                         = humanName,
	noChaseCategory              = "VTOL",
	objectName                   = objectName,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = explodeAs,
	side                         = "CORE",
	sightDistance                = 800,
	smoothAnim                   = true,
	stealth			             = true,
	seismicSignature             = 2,
	transportbyenemy             = false;
	unitname                     = unitName,
	upright                      = false,
	workerTime                   = 0,
	--------------
	-- Movement --
	--------------
	acceleration 				 = 2,
	brakeRate                    = 0.1,
	turninplace 				 = false,
	turninplacespeedlimit 		 = 10,
	turnInPlaceAngleLimit		 = 90,
	turnrate 				 	 = 250,
	--------------
	--------------
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:gdhcannon",
			"custom:emptydirt",
			"custom:blacksmoke",
		},
	},
	sounds                       = {
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = "railgun",
			badTargetCategory     = "BUILDING",
			onlyTargetCategory    = "GROUND BUILDING",
		},
		[2]                      = {
			def                  = "lasercannon",
			badTargetCategory     = "BUILDING",
			onlyTargetCategory    = "GROUND BUILDING",
		},
		[3]                      = {
			def                  = "clusterrockets",
			badTargetCategory     = "BUILDING",
			onlyTargetCategory    = "GROUND BUILDING",
		},
		[4]                      = {
			def                  = "clusterrockets",
			badTargetCategory     = "BUILDING",
			onlyTargetCategory    = "GROUND BUILDING",
		},
	},
	customParams                 = {
		unittype				 = "mobile",
		unitrole				 = "Assault",
		canbetransported 		 = "true",
		needed_cover             = 3,
		death_sounds             = "generic",
		RequireTech              = tech,
		nofriendlyfire	         = "1",
		supply_cost              = 1,
		normaltex                = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		factionname	             = "Loz Alliance",
		corpse                   = "energycore",
	}
}

weaponDefs                 = {
	railgun               = {
		areaofeffect		   = 15,
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		cegTag                 = "railgun",
		rgbColor               = "0.133 0 0.4",
		rgbColor2              = "0.75 0.75 0.75",
		explosionGenerator     = "custom:genericshellexplosion-medium-sparks-burn",
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.25,
		impulseFactor          = 0,
		interceptedByShieldType  = 4,
		name                   = "Railgun",
		range                  = 800,
		reloadtime             = 4,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "weapons/mammothrailgun.wav",
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.4,
		thickness              = 6,
		tolerance              = 10000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 2000,
		customparams             = {
			single_hit		 	 = true,
			expl_light_color	= blue, -- As a string, RGB
			expl_light_radius	= largeExplosion, -- In Elmos
			expl_light_life		= largeExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                   = {
			default              = 1000,
		},
	},
	lasercannon                = {
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		cegTag                 = "railgun",
		rgbColor               = "1 0 0",
		rgbColor2              = "1 1 1",
		explosionGenerator     = "custom:genericshellexplosion-small-sparks-burn",
		edgeEffectiveness	   = 1,
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.1,
		impulseFactor          = 0,
		interceptedByShieldType  = 4,
		name                   = "E.M.G.",
		range                  = 800,
		reloadtime             = 0.5,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "weapons/Sci Fi Blaster 1.wav",
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.25,
		thickness              = 3,
		tolerance              = 10000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 800,
		customparams             = {
			expl_light_color	= red, -- As a string, RGB
			expl_light_radius	= smallExplosion, -- In Elmos
			expl_light_life		= smallExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                   = {
			default              = 30,
		},
	},
	clusterrockets             = {
		AreaOfEffect             = 25,
		avoidFriendly            = false,
		avoidFeature             = false,
		collideFriendly          = false,
		collideFeature           = false,
		cegTag                   = "amphibrocktrail-optimized",
		explosionGenerator       = "custom:genericshellexplosion-small-red",
		burst 					 = 5,
		burstrate 				 = 0.1,
		energypershot            = 0,
		fireStarter              = 70,
		tracks                   = true,
		impulseFactor            = 0,
		interceptedByShieldType  = 4,
		model                    = "missilesmalllauncher.s3o",
		name                     = "Rockets",
		range                    = 800,
		reloadtime               = 5,
		weaponType		         = "MissileLauncher",
		smokeTrail               = false,
		soundStart               = "weapons/rocket1.wav",
		soundHit                 = "explosions/explode5.wav",
		startVelocity            = 300,
		tolerance                = 2000,
		turnrate                 = 2500,
		turret                   = true,
		trajectoryHeight		 = 1.5,
		weaponAcceleration       = 300,
		flightTime               = 10,
		weaponVelocity           = 300,
		sprayangle				 = 5000,
		customparams             = {
			expl_light_color	= red, -- As a string, RGB
			expl_light_radius	= mediumExplosion, -- In Elmos
			expl_light_life		= smallExplosionTTL, -- In frames I.E. 30 frames = 1 second
			expl_light_opacity  = 0.25, -- Use this sparingly
		},
		damage                   = {
			default              = 50,
		},
	},
}
