unitDef                    = {
	acceleration                 = 0.18,
	brakeRate                    = 0.1,
	buildCostEnergy              = 0,
	buildCostMetal               = 6500,
	builder                      = false,
	buildTime                    = 5,
	buildpic					 = "lozsilverback.png",
	canAttack                    = true,
	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = "1",
	category                     = "ARMORED AMPHIB SKIRMISHER",
	description                  = [[Endbringer Class Mobile Target Evaporator]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = explodeAs,
	footprintX                   = 6,
	footprintZ                   = 6,
	iconType                     = "leveller",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	leaveTracks                  = false,
	maxDamage                    = 20000,
	maxSlope                     = 28,
	maxVelocity                  = 1.4,
	maxReverseVelocity           = 1,
	maxWaterDepth                = 25,
	metalStorage                 = 0,
	movementClass                = "TANK6",
	name                         = humanName,
	noChaseCategory              = "VTOL",
	objectName                   = objectName,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = explodeAs,
	side                         = "CORE",
	sightDistance                = 1200,
	smoothAnim                   = true,
	stealth			             = true,
	seismicSignature             = 4,
	transportbyenemy             = false;
	turnInPlace                  = true,
	turnRate                     = 5000,
	unitname                     = unitName,
	workerTime                   = 0,
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:gdhcannon",
			"custom:emptydirt",
			"custom:blacksmoke",
		},
	},
	sounds                       = {
		underattack              = "other/UnitsUnderattack1.wav",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = "heavyrailgun",
		},
		[2]                      = {
			def                  = "railgun",
		},
		[3]                      = {
			def                  = "railgun",
		},
		[4]                      = {
			def                  = "gatling",
		},
		[5]                      = {
			def                  = "gatling",
		},
		[6]                      = {
			def                  = "shield",
		},
	},
	customParams                 = {
		isupgraded			  	 = isUpgraded,
		unittype				 = "mobile",
		unitrole				 = "assault",
		death_sounds             = "generic",
		RequireTech              = tech,
		nofriendlyfire	         = "1",
		supply_cost              = 1,
		normaltex               = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		factionname	             = "Loz Alliance",
		corpse                   = "energycore",
	},
}

weaponDefs                 = {
	heavyrailgun              = {
		areaofeffect		   = 50,
		avoidFriendly            = false,
		avoidFeature             = false,
		collideFriendly          = false,
		collideFeature           = false,
		cegTag               	  = "railgun",
		beamTime                 = 0.1,
		coreThickness            = 0.5,
		duration                 = 0.1,
		explosionGenerator       = "custom:genericshellexplosion-large-red",
		fallOffRate              = 0,
		fireStarter              = 100,
		interceptedByShieldType  = 4,
		impulseFactor            = 0.1,
		minintensity             = 1,
		name                     = "Anti-Tank Laser",
		range                    = 1200,
		reloadtime               = 10,
		WeaponType               = "LaserCannon",
		rgbColor                 = "1 0 0",
		rgbColor2                = "0.8 0.8 0.8",
		soundTrigger             = true,
		soundstart               = "weapons/tankdestroyermaingunfire.wav",
		texture1                 = "pulseshot2",
		texture2                 = "empty",
		thickness                = 9,
		tolerance                = 1000,
		turret                   = true,
		weaponVelocity           = 4000,
		customparams             = {
		}, 
		damage                   = {
			default              = 3000,
		},
	},

	railgun               = {
		areaofeffect		   = 25,
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		cegTag                 = "railgun",
		rgbColor               = "0.133 0 0.4",
		rgbColor2              = "0.75 0.75 0.75",
		explosionGenerator     = "custom:genericshellexplosion-medium-purple",
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.25,
		impulseFactor          = 0,
		minintensity             = 1,
		interceptedByShieldType  = 4,
		name                   = "Railgun",
		range                  = 1200,
		reloadtime             = 1,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "weapons/plasma3c.wav",
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.4,
		thickness              = 6,
		tolerance              = 10000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 2000,
		customparams             = {
			single_hit		 	 = true,
		},
		damage                   = {
			default              = 200,
		},
	},
	gatling                   = {
		avoidFriendly          = false,
		avoidFeature 		   = false,
		collideFriendly        = false,
		collideFeature         = false,
		rgbColor               = "0.5 0.5 0",
		rgbColor2              = "1 1 1",
		explosionGenerator     = "custom:genericshellexplosion-small-sparks-burn",
		edgeEffectiveness	   = 1,
		energypershot          = 0,
		fallOffRate            = 0,
		duration			   = 0.05,
		impulseFactor          = 0,
		interceptedByShieldType  = 4,
		name                   = "Laser Cannon",
		range                  = 1200,
		reloadtime             = 0.1,
		--projectiles			   = 5,
		weaponType		       = "LaserCannon",
		soundStart             = "weapons/Sci Fi Blaster 4.wav",
		sprayangle			   = 750,
		texture1               = "shot",
		texture2               = "empty",
		coreThickness          = 0.5,
		thickness              = 2,
		tolerance              = 2000,
		turret                 = true,
		weaponTimer            = 1,
		weaponVelocity         = 500,
		customparams             = {

		},
		damage                   = {
			default              = 2,
		},
	},

	shield                        = {

		Smartshield               = true,
		Exteriorshield            = true,
		Visibleshield             = false,
		Visibleshieldrepulse      = false,
		ShieldStartingPower       = 0,
		Shieldenergyuse           = 0,
		Shieldradius              = 350,
		Shieldpower               = shield1Power,
		Shieldpowerregen          = shield1PowerRegen,
		Shieldpowerregenenergy    = shield1PowerRegenEnergy,
		Shieldintercepttype       = 4,
		Shieldgoodcolor           = "0.0 0.2 1.0",
		Shieldbadcolor            = "1.0 0 0",
		Shieldalpha              = 0.2,

		texture1		          = "shield4",

		visibleShieldHitFrames    = 1,
		weaponType                = [[Shield]],
		damage                    = {
			default               = 1,
		},
	},
}
