unitDef                     = {
	acceleration                  = 0,
	activateWhenBuilt             = true,
	autoHeal                      = 10,
	blocking                      = false,
	brakeRate                     = 0,
	buildCostEnergy               = 25000,
	buildCostMetal                = 10000,
	builddistance                 = 90,
	buildTime                     = 10500,
	category                      = "BUILDING",
	canMove                       = false,
	canSelfDestruct               = false,
	capturable                    = false,
	cantBeTransported             = false,
	collisionVolumeOffsets        = "0 0 0",
	collisionVolumeScales         = "0 0 0",
	collisionVolumeType           = "box",
	description                   = [[Spawner]],
	energyStorage                 = 1000,
	explodeAs                     = "commnuke_up1",
	footprintX                    = 10,
	footprintZ                    = 10,
	idleAutoHeal                  = 10,
	idleTime                      = 90,
	iconType                     = "commander",
	levelGround                   = true,
	mass                          = 165.75,
	maxDamage                     = 2000,
	maxSlope                      = 20,
	maxVelocity                   = 0,
	name                          = humanName,
	noAutoFire                    = false,
	objectName                    = objectName,
	radarDistance                 = 0,
	script						  = script,
	seismicSignature               = 4,
	selfDestructCountdown         = 1,
	sightDistance                 = 0,
	smoothAnim                    = true,
	transportByEnemy              = false,
	turnInPlace                   = true,
	turnInPlaceAngleLimit         = 90,
	turnRate                      = 0,
	unitname                      = engineUnitName,
	upright                       = true,
	waterline                     = 0,
	workerTime                    = 1500,
	yardMap                       = "yyyyyyyyyy yyyyyyyyyy yyyyyyyyyy yyyyyyyyyy yyyyyyyyyy yyyyyyyyyy yyyyyyyyyy yyyyyyyyyy yyyyyyyyyy yyyyyyyyyy",

	sfxtypes                      = {
		explosiongenerators       = {
			-- [1] = "custom:PurpleLight",
		},
	},

	featureDefs                   = {},

	customParams                  = {
		unittype				 = "building",
		unitrole 				 = "Commander",
		death_sounds             = "commander",
		factionname	             = "Neutral",
		isairbase                = true,
		normaltex                = "unittextures/scavbeacon_normals.dds",
		armortype                = "building",
		iscommander              = true,
		shownametag              = false,
		unitguide = [[The spawn beacon is very tough to kill, but doing so will push back the invasion. The more beacons that exist on the field, the more enemies you will have to contend with. As the enemy territory expands, so do the number of beacons.]],
	},
}
